// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayer.Repository;

#nullable disable

namespace NLayer.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220715183322_appUser")]
    partial class appUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NLayer.Core.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("AppUserProfile");
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 11, 5, 21, 2, 22, 964, DateTimeKind.Unspecified).AddTicks(1098),
                            Name = "Grocery",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 6, 13, 6, 27, 30, 92, DateTimeKind.Unspecified).AddTicks(5113),
                            Name = "Jewelery",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 6, 19, 3, 43, 59, 872, DateTimeKind.Unspecified).AddTicks(8155),
                            Name = "Electronics",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 12, 24, 2, 0, 8, 275, DateTimeKind.Unspecified).AddTicks(7508),
                            Name = "Baby",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 3, 19, 11, 4, 0, 395, DateTimeKind.Unspecified).AddTicks(9135),
                            Name = "Tools",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 1, 2, 6, 11, 24, 51, DateTimeKind.Unspecified).AddTicks(709),
                            Name = "Beauty",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2021, 3, 27, 9, 43, 19, 142, DateTimeKind.Unspecified).AddTicks(8149),
                            Name = "Electronics",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 2, 22, 9, 59, 41, 599, DateTimeKind.Unspecified).AddTicks(8335),
                            Name = "Shoes",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 4, 28, 10, 34, 23, 671, DateTimeKind.Unspecified).AddTicks(5616),
                            Name = "Shoes",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2022, 2, 18, 18, 50, 31, 652, DateTimeKind.Unspecified).AddTicks(6844),
                            Name = "Shoes",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Urunler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 2, 13, 21, 15, 40, 368, DateTimeKind.Unspecified).AddTicks(1349),
                            Name = "Practical Rubber Car",
                            Price = 57m,
                            Status = 1,
                            Stock = 24
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 6, 12, 22, 41, 10, 444, DateTimeKind.Unspecified).AddTicks(7620),
                            Name = "Licensed Soft Chips",
                            Price = 50m,
                            Status = 1,
                            Stock = 68
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 2, 22, 18, 0, 5, 769, DateTimeKind.Unspecified).AddTicks(4086),
                            Name = "Awesome Plastic Pants",
                            Price = 57m,
                            Status = 1,
                            Stock = 47
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2021, 8, 9, 20, 30, 0, 861, DateTimeKind.Unspecified).AddTicks(678),
                            Name = "Gorgeous Rubber Keyboard",
                            Price = 54m,
                            Status = 1,
                            Stock = 153
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 6, 27, 18, 48, 20, 908, DateTimeKind.Unspecified).AddTicks(4138),
                            Name = "Sleek Rubber Car",
                            Price = 52m,
                            Status = 1,
                            Stock = 55
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 2, 18, 0, 30, 19, 984, DateTimeKind.Unspecified).AddTicks(6069),
                            Name = "Practical Plastic Towels",
                            Price = 55m,
                            Status = 1,
                            Stock = 154
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 12, 27, 7, 30, 44, 651, DateTimeKind.Unspecified).AddTicks(2735),
                            Name = "Small Cotton Chair",
                            Price = 50m,
                            Status = 1,
                            Stock = 199
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 3, 13, 1, 33, 5, 813, DateTimeKind.Unspecified).AddTicks(52),
                            Name = "Refined Metal Car",
                            Price = 49m,
                            Status = 1,
                            Stock = 75
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 1, 28, 0, 42, 25, 916, DateTimeKind.Unspecified).AddTicks(9486),
                            Name = "Refined Plastic Mouse",
                            Price = 50m,
                            Status = 1,
                            Stock = 103
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 5, 17, 15, 39, 56, 890, DateTimeKind.Unspecified).AddTicks(4064),
                            Name = "Sleek Cotton Chips",
                            Price = 57m,
                            Status = 1,
                            Stock = 170
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 4, 2, 1, 11, 10, 462, DateTimeKind.Unspecified).AddTicks(3359),
                            Name = "Unbranded Concrete Chair",
                            Price = 54m,
                            Status = 1,
                            Stock = 135
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2021, 11, 7, 5, 49, 51, 272, DateTimeKind.Unspecified).AddTicks(4677),
                            Name = "Licensed Granite Salad",
                            Price = 55m,
                            Status = 1,
                            Stock = 108
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2021, 6, 29, 13, 31, 40, 81, DateTimeKind.Unspecified).AddTicks(1143),
                            Name = "Ergonomic Granite Fish",
                            Price = 56m,
                            Status = 1,
                            Stock = 117
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 6, 4, 9, 37, 37, 699, DateTimeKind.Unspecified).AddTicks(8941),
                            Name = "Generic Wooden Chair",
                            Price = 53m,
                            Status = 1,
                            Stock = 162
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 12, 20, 22, 5, 57, 152, DateTimeKind.Unspecified).AddTicks(3965),
                            Name = "Licensed Granite Bike",
                            Price = 55m,
                            Status = 1,
                            Stock = 96
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2021, 12, 14, 11, 14, 10, 186, DateTimeKind.Unspecified).AddTicks(6471),
                            Name = "Gorgeous Wooden Bacon",
                            Price = 55m,
                            Status = 1,
                            Stock = 26
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 3, 31, 21, 19, 43, 654, DateTimeKind.Unspecified).AddTicks(4680),
                            Name = "Licensed Metal Chicken",
                            Price = 56m,
                            Status = 1,
                            Stock = 3
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 7, 2, 7, 52, 23, 569, DateTimeKind.Unspecified).AddTicks(9588),
                            Name = "Licensed Granite Soap",
                            Price = 53m,
                            Status = 1,
                            Stock = 54
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 12, 14, 4, 13, 52, 405, DateTimeKind.Unspecified).AddTicks(7666),
                            Name = "Generic Metal Tuna",
                            Price = 57m,
                            Status = 1,
                            Stock = 5
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 9, 2, 12, 26, 6, 612, DateTimeKind.Unspecified).AddTicks(2277),
                            Name = "Ergonomic Wooden Towels",
                            Price = 53m,
                            Status = 1,
                            Stock = 97
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 8, 5, 11, 6, 8, 342, DateTimeKind.Unspecified).AddTicks(5002),
                            Name = "Gorgeous Rubber Pants",
                            Price = 57m,
                            Status = 1,
                            Stock = 101
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2022, 1, 24, 17, 42, 32, 836, DateTimeKind.Unspecified).AddTicks(6543),
                            Name = "Awesome Rubber Towels",
                            Price = 51m,
                            Status = 1,
                            Stock = 35
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 3, 23, 35, 21, 224, DateTimeKind.Unspecified).AddTicks(7152),
                            Name = "Refined Fresh Pants",
                            Price = 49m,
                            Status = 1,
                            Stock = 105
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 4, 26, 13, 25, 2, 755, DateTimeKind.Unspecified).AddTicks(4907),
                            Name = "Handmade Cotton Towels",
                            Price = 56m,
                            Status = 1,
                            Stock = 61
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2021, 6, 22, 4, 4, 35, 355, DateTimeKind.Unspecified).AddTicks(8102),
                            Name = "Generic Steel Bacon",
                            Price = 54m,
                            Status = 1,
                            Stock = 48
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 12, 2, 8, 27, 681, DateTimeKind.Unspecified).AddTicks(3366),
                            Name = "Fantastic Frozen Pants",
                            Price = 55m,
                            Status = 1,
                            Stock = 146
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 7, 20, 14, 31, 27, 976, DateTimeKind.Unspecified).AddTicks(8896),
                            Name = "Unbranded Granite Car",
                            Price = 54m,
                            Status = 1,
                            Stock = 97
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 5, 23, 17, 6, 25, 970, DateTimeKind.Unspecified).AddTicks(7120),
                            Name = "Intelligent Rubber Shoes",
                            Price = 54m,
                            Status = 1,
                            Stock = 198
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2021, 4, 3, 16, 55, 16, 353, DateTimeKind.Unspecified).AddTicks(8865),
                            Name = "Sleek Steel Soap",
                            Price = 57m,
                            Status = 1,
                            Stock = 130
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 8, 10, 8, 41, 17, 933, DateTimeKind.Unspecified).AddTicks(9939),
                            Name = "Practical Metal Chicken",
                            Price = 55m,
                            Status = 1,
                            Stock = 42
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UrunOzellikleri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#63062b",
                            CreatedDate = new DateTime(2022, 2, 7, 4, 41, 21, 587, DateTimeKind.Unspecified).AddTicks(955),
                            Height = 65,
                            Status = 1,
                            Width = 145
                        },
                        new
                        {
                            Id = 2,
                            Color = "#251f29",
                            CreatedDate = new DateTime(2022, 4, 15, 21, 24, 59, 573, DateTimeKind.Unspecified).AddTicks(7298),
                            Height = 181,
                            Status = 1,
                            Width = 156
                        },
                        new
                        {
                            Id = 3,
                            Color = "#60024e",
                            CreatedDate = new DateTime(2021, 7, 6, 2, 1, 58, 705, DateTimeKind.Unspecified).AddTicks(6997),
                            Height = 71,
                            Status = 1,
                            Width = 156
                        },
                        new
                        {
                            Id = 4,
                            Color = "#4a402f",
                            CreatedDate = new DateTime(2021, 7, 29, 9, 37, 31, 482, DateTimeKind.Unspecified).AddTicks(2507),
                            Height = 115,
                            Status = 1,
                            Width = 10
                        },
                        new
                        {
                            Id = 5,
                            Color = "#3d6475",
                            CreatedDate = new DateTime(2021, 11, 14, 7, 39, 13, 909, DateTimeKind.Unspecified).AddTicks(7956),
                            Height = 40,
                            Status = 1,
                            Width = 127
                        },
                        new
                        {
                            Id = 6,
                            Color = "#3f397d",
                            CreatedDate = new DateTime(2021, 3, 31, 21, 17, 14, 605, DateTimeKind.Unspecified).AddTicks(816),
                            Height = 68,
                            Status = 1,
                            Width = 24
                        },
                        new
                        {
                            Id = 7,
                            Color = "#481560",
                            CreatedDate = new DateTime(2021, 4, 21, 21, 39, 47, 127, DateTimeKind.Unspecified).AddTicks(4378),
                            Height = 121,
                            Status = 1,
                            Width = 26
                        },
                        new
                        {
                            Id = 8,
                            Color = "#694a4d",
                            CreatedDate = new DateTime(2022, 3, 15, 17, 46, 18, 23, DateTimeKind.Unspecified).AddTicks(8612),
                            Height = 30,
                            Status = 1,
                            Width = 143
                        },
                        new
                        {
                            Id = 9,
                            Color = "#6b4a60",
                            CreatedDate = new DateTime(2021, 8, 3, 17, 57, 35, 718, DateTimeKind.Unspecified).AddTicks(1143),
                            Height = 140,
                            Status = 1,
                            Width = 147
                        },
                        new
                        {
                            Id = 10,
                            Color = "#044423",
                            CreatedDate = new DateTime(2021, 6, 15, 15, 32, 9, 310, DateTimeKind.Unspecified).AddTicks(3844),
                            Height = 87,
                            Status = 1,
                            Width = 81
                        },
                        new
                        {
                            Id = 11,
                            Color = "#4e277c",
                            CreatedDate = new DateTime(2021, 6, 19, 21, 37, 51, 808, DateTimeKind.Unspecified).AddTicks(1654),
                            Height = 22,
                            Status = 1,
                            Width = 165
                        },
                        new
                        {
                            Id = 12,
                            Color = "#546645",
                            CreatedDate = new DateTime(2022, 7, 1, 10, 40, 59, 665, DateTimeKind.Unspecified).AddTicks(2753),
                            Height = 178,
                            Status = 1,
                            Width = 161
                        },
                        new
                        {
                            Id = 13,
                            Color = "#6c7d1d",
                            CreatedDate = new DateTime(2022, 5, 14, 22, 37, 32, 276, DateTimeKind.Unspecified).AddTicks(7812),
                            Height = 107,
                            Status = 1,
                            Width = 9
                        },
                        new
                        {
                            Id = 14,
                            Color = "#1e4906",
                            CreatedDate = new DateTime(2021, 6, 8, 5, 16, 34, 900, DateTimeKind.Unspecified).AddTicks(8666),
                            Height = 79,
                            Status = 1,
                            Width = 131
                        },
                        new
                        {
                            Id = 15,
                            Color = "#6c045c",
                            CreatedDate = new DateTime(2022, 6, 29, 11, 17, 21, 855, DateTimeKind.Unspecified).AddTicks(2086),
                            Height = 13,
                            Status = 1,
                            Width = 89
                        },
                        new
                        {
                            Id = 16,
                            Color = "#0d0a09",
                            CreatedDate = new DateTime(2021, 5, 21, 11, 38, 31, 584, DateTimeKind.Unspecified).AddTicks(9626),
                            Height = 128,
                            Status = 1,
                            Width = 77
                        },
                        new
                        {
                            Id = 17,
                            Color = "#2a3e43",
                            CreatedDate = new DateTime(2022, 6, 8, 13, 50, 55, 691, DateTimeKind.Unspecified).AddTicks(5638),
                            Height = 139,
                            Status = 1,
                            Width = 28
                        },
                        new
                        {
                            Id = 18,
                            Color = "#653611",
                            CreatedDate = new DateTime(2022, 4, 14, 20, 56, 20, 991, DateTimeKind.Unspecified).AddTicks(7325),
                            Height = 129,
                            Status = 1,
                            Width = 86
                        },
                        new
                        {
                            Id = 19,
                            Color = "#4a3312",
                            CreatedDate = new DateTime(2021, 10, 18, 22, 45, 21, 621, DateTimeKind.Unspecified).AddTicks(3486),
                            Height = 114,
                            Status = 1,
                            Width = 56
                        },
                        new
                        {
                            Id = 20,
                            Color = "#787e73",
                            CreatedDate = new DateTime(2021, 9, 16, 17, 40, 27, 647, DateTimeKind.Unspecified).AddTicks(4855),
                            Height = 92,
                            Status = 1,
                            Width = 129
                        },
                        new
                        {
                            Id = 21,
                            Color = "#050e4e",
                            CreatedDate = new DateTime(2021, 12, 17, 15, 12, 32, 253, DateTimeKind.Unspecified).AddTicks(7853),
                            Height = 66,
                            Status = 1,
                            Width = 45
                        },
                        new
                        {
                            Id = 22,
                            Color = "#1c0a63",
                            CreatedDate = new DateTime(2021, 7, 31, 20, 57, 13, 923, DateTimeKind.Unspecified).AddTicks(8823),
                            Height = 142,
                            Status = 1,
                            Width = 123
                        },
                        new
                        {
                            Id = 23,
                            Color = "#1e201d",
                            CreatedDate = new DateTime(2021, 10, 3, 2, 24, 56, 549, DateTimeKind.Unspecified).AddTicks(3734),
                            Height = 11,
                            Status = 1,
                            Width = 163
                        },
                        new
                        {
                            Id = 24,
                            Color = "#3f3800",
                            CreatedDate = new DateTime(2021, 7, 12, 0, 59, 11, 318, DateTimeKind.Unspecified).AddTicks(2391),
                            Height = 55,
                            Status = 1,
                            Width = 134
                        },
                        new
                        {
                            Id = 25,
                            Color = "#6b6617",
                            CreatedDate = new DateTime(2021, 8, 6, 16, 18, 25, 956, DateTimeKind.Unspecified).AddTicks(9839),
                            Height = 14,
                            Status = 1,
                            Width = 109
                        },
                        new
                        {
                            Id = 26,
                            Color = "#2a0673",
                            CreatedDate = new DateTime(2022, 3, 16, 20, 51, 4, 884, DateTimeKind.Unspecified).AddTicks(2768),
                            Height = 144,
                            Status = 1,
                            Width = 182
                        },
                        new
                        {
                            Id = 27,
                            Color = "#1c1c38",
                            CreatedDate = new DateTime(2021, 5, 5, 11, 18, 19, 916, DateTimeKind.Unspecified).AddTicks(8469),
                            Height = 37,
                            Status = 1,
                            Width = 19
                        },
                        new
                        {
                            Id = 28,
                            Color = "#3e2928",
                            CreatedDate = new DateTime(2021, 4, 9, 6, 39, 42, 903, DateTimeKind.Unspecified).AddTicks(9620),
                            Height = 199,
                            Status = 1,
                            Width = 72
                        },
                        new
                        {
                            Id = 29,
                            Color = "#730948",
                            CreatedDate = new DateTime(2021, 5, 14, 10, 50, 30, 526, DateTimeKind.Unspecified).AddTicks(2240),
                            Height = 129,
                            Status = 1,
                            Width = 144
                        },
                        new
                        {
                            Id = 30,
                            Color = "#4f7c47",
                            CreatedDate = new DateTime(2022, 3, 7, 17, 21, 18, 138, DateTimeKind.Unspecified).AddTicks(8764),
                            Height = 53,
                            Status = 1,
                            Width = 54
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserProfile", b =>
                {
                    b.HasOne("NLayer.Core.Models.AppUser", "AppUser")
                        .WithOne("AppUserProfile")
                        .HasForeignKey("NLayer.Core.Models.AppUserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.HasOne("NLayer.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.HasOne("NLayer.Core.Models.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("NLayer.Core.Models.ProductFeature", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUser", b =>
                {
                    b.Navigation("AppUserProfile");
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Navigation("ProductFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
