// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayer.Repository;

#nullable disable

namespace NLayer.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221207222248_NewMigs89")]
    partial class NewMigs89
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NLayer.Core.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivationCode = new Guid("eaf41c8c-3d98-4c9e-8761-9680c76f19fe"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 9, 12, 22, 18, 11, 42, DateTimeKind.Unspecified).AddTicks(3318),
                            Status = 1,
                            UserName = "Yvette_Stoltenberg7"
                        },
                        new
                        {
                            Id = 2,
                            ActivationCode = new Guid("287a7dfe-8fbd-41ca-ab43-00dfa1a29976"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 3, 24, 13, 30, 49, 705, DateTimeKind.Unspecified).AddTicks(9769),
                            Status = 1,
                            UserName = "Jarret_Feeney"
                        },
                        new
                        {
                            Id = 3,
                            ActivationCode = new Guid("999275ad-ff37-43a2-a440-44bad87aeab0"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 3, 21, 14, 5, 39, 255, DateTimeKind.Unspecified).AddTicks(4865),
                            Status = 1,
                            UserName = "Lue35"
                        },
                        new
                        {
                            Id = 4,
                            ActivationCode = new Guid("0ca8dac3-f6ae-4e3e-ad2f-7d314e70ddc7"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 10, 13, 18, 46, 8, 6, DateTimeKind.Unspecified).AddTicks(534),
                            Status = 1,
                            UserName = "Zita.Harris"
                        },
                        new
                        {
                            Id = 5,
                            ActivationCode = new Guid("bfb2ab5e-4b48-4e0c-ab51-8b3574505e27"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 7, 2, 1, 1, 37, 209, DateTimeKind.Unspecified).AddTicks(7486),
                            Status = 1,
                            UserName = "Lonie.Rolfson"
                        },
                        new
                        {
                            Id = 6,
                            ActivationCode = new Guid("7f3474f9-7f5c-4d3f-a63e-8e3415205282"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 9, 10, 14, 22, 35, 666, DateTimeKind.Unspecified).AddTicks(2183),
                            Status = 1,
                            UserName = "Rozella.Gislason75"
                        },
                        new
                        {
                            Id = 7,
                            ActivationCode = new Guid("626a4996-d19c-4bc5-bd57-77bacd47cf94"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 9, 26, 15, 41, 50, 288, DateTimeKind.Unspecified).AddTicks(6585),
                            Status = 1,
                            UserName = "Katarina_Metz47"
                        },
                        new
                        {
                            Id = 8,
                            ActivationCode = new Guid("a67af677-8127-41a0-849d-3d8c73658b78"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 3, 28, 2, 53, 42, 300, DateTimeKind.Unspecified).AddTicks(5269),
                            Status = 1,
                            UserName = "Violet_Wisozk"
                        },
                        new
                        {
                            Id = 9,
                            ActivationCode = new Guid("50d79478-3e64-4cbb-aab0-cad8f11248d1"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 6, 20, 7, 32, 7, 872, DateTimeKind.Unspecified).AddTicks(9940),
                            Status = 1,
                            UserName = "Lesly.Johnson68"
                        },
                        new
                        {
                            Id = 10,
                            ActivationCode = new Guid("ba0ac7df-8310-4111-9b05-6da63d3efb48"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 10, 5, 8, 1, 43, 893, DateTimeKind.Unspecified).AddTicks(3690),
                            Status = 1,
                            UserName = "Maegan.Wiza"
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserLanguage", b =>
                {
                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GivenBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("LanguageID", "AppUserID");

                    b.HasIndex("AppUserID");

                    b.ToTable("AppUsersLanguages");

                    b.HasData(
                        new
                        {
                            LanguageID = 1,
                            AppUserID = 1,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1291),
                            GivenBy = "Rex22",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 2,
                            AppUserID = 1,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1350),
                            GivenBy = "Prudence.Olson83",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 3,
                            AppUserID = 1,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1402),
                            GivenBy = "Colleen_Kohler",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 4,
                            AppUserID = 1,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1458),
                            GivenBy = "Janice.Sipes12",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 5,
                            AppUserID = 1,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1507),
                            GivenBy = "Colleen_Harvey42",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 6,
                            AppUserID = 1,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1556),
                            GivenBy = "Fleta.Sipes15",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 7,
                            AppUserID = 1,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1624),
                            GivenBy = "Xander.Ferry83",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 8,
                            AppUserID = 1,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1675),
                            GivenBy = "Clifford.Dach",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 1,
                            AppUserID = 2,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1728),
                            GivenBy = "Fabiola21",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 2,
                            AppUserID = 2,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1780),
                            GivenBy = "Ryleigh78",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 3,
                            AppUserID = 2,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1835),
                            GivenBy = "Adalberto.Stokes",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 4,
                            AppUserID = 2,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1889),
                            GivenBy = "Sally.Dickinson76",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 5,
                            AppUserID = 2,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1936),
                            GivenBy = "Oran8",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 6,
                            AppUserID = 2,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1994),
                            GivenBy = "Makenzie_Dietrich35",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 7,
                            AppUserID = 2,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(2202),
                            GivenBy = "Sadye_Schaefer",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 8,
                            AppUserID = 2,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(2271),
                            GivenBy = "Elnora_Welch",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 1,
                            AppUserID = 3,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(2343),
                            GivenBy = "Cade.Boyer97",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 2,
                            AppUserID = 3,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(2415),
                            GivenBy = "Briana54",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 3,
                            AppUserID = 3,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(2530),
                            GivenBy = "Destiney.DAmore26",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 4,
                            AppUserID = 3,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(2610),
                            GivenBy = "Hortense.Fisher2",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 5,
                            AppUserID = 3,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(2703),
                            GivenBy = "Drew22",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 6,
                            AppUserID = 3,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(2778),
                            GivenBy = "Michele48",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 7,
                            AppUserID = 3,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3004),
                            GivenBy = "Linda.Schaden",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 8,
                            AppUserID = 3,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3077),
                            GivenBy = "Eliza.Crooks",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 1,
                            AppUserID = 4,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3149),
                            GivenBy = "Sarai36",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 2,
                            AppUserID = 4,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3222),
                            GivenBy = "Griffin_Kessler",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 3,
                            AppUserID = 4,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3289),
                            GivenBy = "Brayan44",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 4,
                            AppUserID = 4,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3407),
                            GivenBy = "Freeda88",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 5,
                            AppUserID = 4,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3475),
                            GivenBy = "Cicero16",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 6,
                            AppUserID = 4,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3564),
                            GivenBy = "Cleora52",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 7,
                            AppUserID = 4,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3628),
                            GivenBy = "Isaias.Crona47",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 8,
                            AppUserID = 4,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3692),
                            GivenBy = "Jamey.Kovacek94",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 1,
                            AppUserID = 5,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3756),
                            GivenBy = "Aliyah.Howell",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 2,
                            AppUserID = 5,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3824),
                            GivenBy = "Luisa_Larkin74",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 3,
                            AppUserID = 5,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3887),
                            GivenBy = "Dewayne7",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 4,
                            AppUserID = 5,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(3954),
                            GivenBy = "Frank.Lindgren33",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 5,
                            AppUserID = 5,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4016),
                            GivenBy = "Joseph72",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 6,
                            AppUserID = 5,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4084),
                            GivenBy = "Wilson_Beatty85",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 7,
                            AppUserID = 5,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4149),
                            GivenBy = "Junius23",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 8,
                            AppUserID = 5,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4215),
                            GivenBy = "Susanna36",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 1,
                            AppUserID = 6,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4289),
                            GivenBy = "Florence_Mitchell",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 2,
                            AppUserID = 6,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4346),
                            GivenBy = "Sincere.Olson",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 3,
                            AppUserID = 6,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4412),
                            GivenBy = "Kassandra_Maggio",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 4,
                            AppUserID = 6,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4479),
                            GivenBy = "Robin60",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 5,
                            AppUserID = 6,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4538),
                            GivenBy = "Rita.Hoppe27",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 6,
                            AppUserID = 6,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4608),
                            GivenBy = "Demario_Bins",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 7,
                            AppUserID = 6,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4679),
                            GivenBy = "Delaney.Kuhic",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 8,
                            AppUserID = 6,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4765),
                            GivenBy = "Mitchell_Baumbach31",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 1,
                            AppUserID = 7,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4841),
                            GivenBy = "Charlotte.Ortiz72",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 2,
                            AppUserID = 7,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4909),
                            GivenBy = "Keith_Keebler",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 3,
                            AppUserID = 7,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(4989),
                            GivenBy = "Johnny6",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 4,
                            AppUserID = 7,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5055),
                            GivenBy = "Kiana_Wiegand",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 5,
                            AppUserID = 7,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5122),
                            GivenBy = "Karolann.Yost",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 6,
                            AppUserID = 7,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5192),
                            GivenBy = "Kenyon38",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 7,
                            AppUserID = 7,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5268),
                            GivenBy = "Lenny55",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 8,
                            AppUserID = 7,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5344),
                            GivenBy = "Marguerite_Weissnat46",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 1,
                            AppUserID = 8,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5410),
                            GivenBy = "Vella.Sauer93",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 2,
                            AppUserID = 8,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5480),
                            GivenBy = "Osvaldo.Walsh",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 3,
                            AppUserID = 8,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5546),
                            GivenBy = "Jack_Herman35",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 4,
                            AppUserID = 8,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5610),
                            GivenBy = "Lynn_Abshire63",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 5,
                            AppUserID = 8,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5681),
                            GivenBy = "Brigitte.Sanford57",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 6,
                            AppUserID = 8,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5755),
                            GivenBy = "Alexanne.Berge",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 7,
                            AppUserID = 8,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5821),
                            GivenBy = "Charley_Prohaska54",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 8,
                            AppUserID = 8,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5885),
                            GivenBy = "Eric95",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 1,
                            AppUserID = 9,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(5963),
                            GivenBy = "Kirstin1",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 2,
                            AppUserID = 9,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6028),
                            GivenBy = "Dora.Hilpert13",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 3,
                            AppUserID = 9,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6096),
                            GivenBy = "Brody.Spencer20",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 4,
                            AppUserID = 9,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6173),
                            GivenBy = "Marianna_Murray36",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 5,
                            AppUserID = 9,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6252),
                            GivenBy = "Trystan.Cartwright44",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 6,
                            AppUserID = 9,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6320),
                            GivenBy = "Nico_Bogan6",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 7,
                            AppUserID = 9,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6392),
                            GivenBy = "Kamren_Mosciski",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 8,
                            AppUserID = 9,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6457),
                            GivenBy = "Lionel_Wehner41",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 1,
                            AppUserID = 10,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6551),
                            GivenBy = "Dangelo22",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 2,
                            AppUserID = 10,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6631),
                            GivenBy = "Maximo_Marvin89",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 3,
                            AppUserID = 10,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6705),
                            GivenBy = "Rosa.Kris6",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 4,
                            AppUserID = 10,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6768),
                            GivenBy = "Rod.Hayes75",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 5,
                            AppUserID = 10,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6832),
                            GivenBy = "Quincy.Ortiz12",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 6,
                            AppUserID = 10,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6912),
                            GivenBy = "Alvah.Bechtelar57",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 7,
                            AppUserID = 10,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(6985),
                            GivenBy = "Mohammad_Schaefer76",
                            Status = 1
                        },
                        new
                        {
                            LanguageID = 8,
                            AppUserID = 10,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(7056),
                            GivenBy = "Jameson_Reilly23",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("AppUserProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 12, 2, 8, 49, 10, 384, DateTimeKind.Unspecified).AddTicks(6722),
                            FirstName = "Margie",
                            LastName = "Hamill",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 12, 31, 4, 21, 20, 584, DateTimeKind.Unspecified).AddTicks(1808),
                            FirstName = "Donna",
                            LastName = "Armstrong",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 11, 14, 14, 48, 10, 846, DateTimeKind.Unspecified).AddTicks(5440),
                            FirstName = "Dominick",
                            LastName = "Williamson",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 4, 12, 21, 33, 32, 527, DateTimeKind.Unspecified).AddTicks(8694),
                            FirstName = "Ed",
                            LastName = "Smitham",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 8, 18, 7, 27, 24, 356, DateTimeKind.Unspecified).AddTicks(1776),
                            FirstName = "Gail",
                            LastName = "Lindgren",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2021, 4, 15, 9, 52, 24, 321, DateTimeKind.Unspecified).AddTicks(5950),
                            FirstName = "Fredrick",
                            LastName = "Cartwright",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 1, 29, 15, 22, 25, 53, DateTimeKind.Unspecified).AddTicks(1236),
                            FirstName = "Brandon",
                            LastName = "Ziemann",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 5, 4, 18, 35, 59, 165, DateTimeKind.Unspecified).AddTicks(4090),
                            FirstName = "Jose",
                            LastName = "Ledner",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2021, 12, 26, 11, 24, 37, 457, DateTimeKind.Unspecified).AddTicks(3189),
                            FirstName = "Bill",
                            LastName = "Von",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2022, 5, 9, 8, 49, 9, 882, DateTimeKind.Unspecified).AddTicks(2961),
                            FirstName = "Casey",
                            LastName = "Harvey",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 11, 4, 20, 44, 8, 933, DateTimeKind.Unspecified).AddTicks(9184),
                            Name = "Outdoors",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 3, 4, 6, 33, 43, 424, DateTimeKind.Unspecified).AddTicks(6915),
                            Name = "Jewelery",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 12, 30, 23, 8, 59, 760, DateTimeKind.Unspecified).AddTicks(1799),
                            Name = "Computers",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 6, 24, 18, 35, 34, 708, DateTimeKind.Unspecified).AddTicks(4695),
                            Name = "Movies",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 8, 5, 5, 48, 39, 290, DateTimeKind.Unspecified).AddTicks(2096),
                            Name = "Books",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2021, 9, 24, 8, 55, 8, 37, DateTimeKind.Unspecified).AddTicks(2399),
                            Name = "Automotive",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2021, 7, 1, 20, 2, 18, 157, DateTimeKind.Unspecified).AddTicks(9119),
                            Name = "Tools",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 9, 22, 10, 1, 50, 494, DateTimeKind.Unspecified).AddTicks(428),
                            Name = "Music",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2021, 9, 20, 7, 36, 21, 137, DateTimeKind.Unspecified).AddTicks(8228),
                            Name = "Baby",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2022, 7, 12, 4, 44, 5, 56, DateTimeKind.Unspecified).AddTicks(3925),
                            Name = "Automotive",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1208),
                            LanguageName = "Turkish",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1211),
                            LanguageName = "German",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1212),
                            LanguageName = "English",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1213),
                            LanguageName = "Korean",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1214),
                            LanguageName = "Finnish",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1216),
                            LanguageName = "French",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1217),
                            LanguageName = "Czech",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 12, 8, 1, 22, 48, 577, DateTimeKind.Local).AddTicks(1218),
                            LanguageName = "Spanish ",
                            Level = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Urunler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 11, 27, 15, 26, 57, 859, DateTimeKind.Unspecified).AddTicks(9412),
                            Name = "Intelligent Fresh Table",
                            Price = 57m,
                            Status = 1,
                            Stock = 103
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 12, 13, 8, 55, 16, 172, DateTimeKind.Unspecified).AddTicks(2318),
                            Name = "Handmade Soft Sausages",
                            Price = 50m,
                            Status = 1,
                            Stock = 92
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 7, 2, 17, 51, 41, 60, DateTimeKind.Unspecified).AddTicks(4444),
                            Name = "Practical Cotton Hat",
                            Price = 57m,
                            Status = 1,
                            Stock = 155
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 3, 24, 9, 15, 46, 467, DateTimeKind.Unspecified).AddTicks(4984),
                            Name = "Small Rubber Gloves",
                            Price = 53m,
                            Status = 1,
                            Stock = 130
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 9, 18, 6, 36, 49, 994, DateTimeKind.Unspecified).AddTicks(6410),
                            Name = "Ergonomic Concrete Chicken",
                            Price = 51m,
                            Status = 1,
                            Stock = 104
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 9, 16, 7, 17, 37, 580, DateTimeKind.Unspecified).AddTicks(3791),
                            Name = "Handcrafted Fresh Mouse",
                            Price = 56m,
                            Status = 1,
                            Stock = 45
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2022, 10, 1, 10, 26, 52, 789, DateTimeKind.Unspecified).AddTicks(6567),
                            Name = "Fantastic Granite Bike",
                            Price = 54m,
                            Status = 1,
                            Stock = 30
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 10, 29, 22, 18, 31, 895, DateTimeKind.Unspecified).AddTicks(2790),
                            Name = "Sleek Concrete Table",
                            Price = 56m,
                            Status = 1,
                            Stock = 152
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 3, 29, 22, 0, 26, 890, DateTimeKind.Unspecified).AddTicks(8020),
                            Name = "Incredible Metal Computer",
                            Price = 53m,
                            Status = 1,
                            Stock = 166
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 6, 1, 6, 47, 41, 20, DateTimeKind.Unspecified).AddTicks(941),
                            Name = "Generic Plastic Ball",
                            Price = 56m,
                            Status = 1,
                            Stock = 26
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 10, 5, 0, 4, 36, 952, DateTimeKind.Unspecified).AddTicks(2162),
                            Name = "Awesome Concrete Car",
                            Price = 53m,
                            Status = 1,
                            Stock = 165
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2022, 1, 27, 11, 50, 19, 434, DateTimeKind.Unspecified).AddTicks(9368),
                            Name = "Small Granite Gloves",
                            Price = 49m,
                            Status = 1,
                            Stock = 165
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 4, 28, 16, 3, 48, 650, DateTimeKind.Unspecified).AddTicks(5635),
                            Name = "Awesome Soft Soap",
                            Price = 53m,
                            Status = 1,
                            Stock = 66
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 9, 13, 16, 18, 45, 87, DateTimeKind.Unspecified).AddTicks(31),
                            Name = "Refined Plastic Ball",
                            Price = 56m,
                            Status = 1,
                            Stock = 16
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 11, 1, 19, 54, 51, 231, DateTimeKind.Unspecified).AddTicks(7638),
                            Name = "Fantastic Cotton Table",
                            Price = 49m,
                            Status = 1,
                            Stock = 76
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 5, 15, 3, 5, 54, 274, DateTimeKind.Unspecified).AddTicks(6115),
                            Name = "Rustic Wooden Chair",
                            Price = 57m,
                            Status = 1,
                            Stock = 117
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 8, 30, 4, 50, 13, 954, DateTimeKind.Unspecified).AddTicks(1615),
                            Name = "Awesome Fresh Chicken",
                            Price = 52m,
                            Status = 1,
                            Stock = 141
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 14, 8, 1, 6, 390, DateTimeKind.Unspecified).AddTicks(5722),
                            Name = "Awesome Metal Fish",
                            Price = 56m,
                            Status = 1,
                            Stock = 62
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2022, 6, 27, 22, 15, 22, 975, DateTimeKind.Unspecified).AddTicks(5918),
                            Name = "Sleek Cotton Table",
                            Price = 56m,
                            Status = 1,
                            Stock = 105
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 11, 13, 22, 3, 18, 950, DateTimeKind.Unspecified).AddTicks(104),
                            Name = "Tasty Soft Cheese",
                            Price = 54m,
                            Status = 1,
                            Stock = 164
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 9, 13, 3, 51, 50, 250, DateTimeKind.Unspecified).AddTicks(4578),
                            Name = "Refined Rubber Car",
                            Price = 55m,
                            Status = 1,
                            Stock = 180
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 8, 23, 1, 8, 25, 29, DateTimeKind.Unspecified).AddTicks(6891),
                            Name = "Ergonomic Rubber Shoes",
                            Price = 56m,
                            Status = 1,
                            Stock = 104
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2022, 6, 26, 9, 27, 10, 379, DateTimeKind.Unspecified).AddTicks(7736),
                            Name = "Ergonomic Wooden Table",
                            Price = 52m,
                            Status = 1,
                            Stock = 141
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 11, 13, 12, 16, 51, 2, DateTimeKind.Unspecified).AddTicks(3990),
                            Name = "Rustic Cotton Shoes",
                            Price = 49m,
                            Status = 1,
                            Stock = 70
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 8, 17, 13, 7, 38, 62, DateTimeKind.Unspecified).AddTicks(9093),
                            Name = "Handcrafted Cotton Tuna",
                            Price = 51m,
                            Status = 1,
                            Stock = 43
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 4, 21, 20, 11, 26, 891, DateTimeKind.Unspecified).AddTicks(3283),
                            Name = "Small Soft Pizza",
                            Price = 52m,
                            Status = 1,
                            Stock = 108
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 5, 9, 7, 21, 2, 780, DateTimeKind.Unspecified).AddTicks(5899),
                            Name = "Refined Metal Tuna",
                            Price = 56m,
                            Status = 1,
                            Stock = 82
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 6, 27, 22, 41, 35, 991, DateTimeKind.Unspecified).AddTicks(7746),
                            Name = "Sleek Wooden Mouse",
                            Price = 51m,
                            Status = 1,
                            Stock = 22
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 10, 23, 22, 59, 37, 153, DateTimeKind.Unspecified).AddTicks(7229),
                            Name = "Tasty Rubber Cheese",
                            Price = 54m,
                            Status = 1,
                            Stock = 123
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 9, 18, 19, 46, 40, 776, DateTimeKind.Unspecified).AddTicks(5131),
                            Name = "Generic Granite Tuna",
                            Price = 54m,
                            Status = 1,
                            Stock = 189
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UrunOzellikleri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#320035",
                            CreatedDate = new DateTime(2022, 7, 27, 2, 15, 10, 948, DateTimeKind.Unspecified).AddTicks(6492),
                            Height = 102,
                            Status = 1,
                            Width = 99
                        },
                        new
                        {
                            Id = 2,
                            Color = "#105a58",
                            CreatedDate = new DateTime(2022, 9, 18, 12, 30, 43, 507, DateTimeKind.Unspecified).AddTicks(5678),
                            Height = 200,
                            Status = 1,
                            Width = 53
                        },
                        new
                        {
                            Id = 3,
                            Color = "#701b67",
                            CreatedDate = new DateTime(2022, 9, 17, 0, 40, 55, 651, DateTimeKind.Unspecified).AddTicks(6007),
                            Height = 159,
                            Status = 1,
                            Width = 21
                        },
                        new
                        {
                            Id = 4,
                            Color = "#523f07",
                            CreatedDate = new DateTime(2022, 11, 8, 15, 45, 46, 209, DateTimeKind.Unspecified).AddTicks(802),
                            Height = 24,
                            Status = 1,
                            Width = 165
                        },
                        new
                        {
                            Id = 5,
                            Color = "#282b57",
                            CreatedDate = new DateTime(2021, 4, 14, 1, 40, 11, 330, DateTimeKind.Unspecified).AddTicks(5489),
                            Height = 71,
                            Status = 1,
                            Width = 200
                        },
                        new
                        {
                            Id = 6,
                            Color = "#7b6a62",
                            CreatedDate = new DateTime(2021, 8, 2, 13, 44, 34, 256, DateTimeKind.Unspecified).AddTicks(8499),
                            Height = 72,
                            Status = 1,
                            Width = 190
                        },
                        new
                        {
                            Id = 7,
                            Color = "#600c76",
                            CreatedDate = new DateTime(2021, 12, 26, 1, 18, 2, 546, DateTimeKind.Unspecified).AddTicks(6197),
                            Height = 150,
                            Status = 1,
                            Width = 117
                        },
                        new
                        {
                            Id = 8,
                            Color = "#361d37",
                            CreatedDate = new DateTime(2021, 10, 21, 3, 17, 38, 926, DateTimeKind.Unspecified).AddTicks(3219),
                            Height = 191,
                            Status = 1,
                            Width = 148
                        },
                        new
                        {
                            Id = 9,
                            Color = "#172978",
                            CreatedDate = new DateTime(2021, 4, 11, 2, 56, 32, 547, DateTimeKind.Unspecified).AddTicks(9551),
                            Height = 1,
                            Status = 1,
                            Width = 130
                        },
                        new
                        {
                            Id = 10,
                            Color = "#151570",
                            CreatedDate = new DateTime(2021, 4, 11, 20, 38, 42, 718, DateTimeKind.Unspecified).AddTicks(4907),
                            Height = 175,
                            Status = 1,
                            Width = 163
                        },
                        new
                        {
                            Id = 11,
                            Color = "#2f7166",
                            CreatedDate = new DateTime(2022, 5, 9, 15, 36, 43, 344, DateTimeKind.Unspecified).AddTicks(6433),
                            Height = 17,
                            Status = 1,
                            Width = 7
                        },
                        new
                        {
                            Id = 12,
                            Color = "#756d27",
                            CreatedDate = new DateTime(2021, 10, 26, 9, 46, 13, 42, DateTimeKind.Unspecified).AddTicks(3943),
                            Height = 57,
                            Status = 1,
                            Width = 150
                        },
                        new
                        {
                            Id = 13,
                            Color = "#623400",
                            CreatedDate = new DateTime(2022, 3, 18, 10, 36, 59, 729, DateTimeKind.Unspecified).AddTicks(9956),
                            Height = 132,
                            Status = 1,
                            Width = 98
                        },
                        new
                        {
                            Id = 14,
                            Color = "#6c1d5b",
                            CreatedDate = new DateTime(2021, 10, 9, 23, 33, 6, 722, DateTimeKind.Unspecified).AddTicks(9766),
                            Height = 134,
                            Status = 1,
                            Width = 175
                        },
                        new
                        {
                            Id = 15,
                            Color = "#6c3461",
                            CreatedDate = new DateTime(2022, 3, 9, 12, 34, 55, 336, DateTimeKind.Unspecified).AddTicks(2269),
                            Height = 169,
                            Status = 1,
                            Width = 87
                        },
                        new
                        {
                            Id = 16,
                            Color = "#134632",
                            CreatedDate = new DateTime(2022, 11, 19, 4, 36, 6, 115, DateTimeKind.Unspecified).AddTicks(4226),
                            Height = 130,
                            Status = 1,
                            Width = 154
                        },
                        new
                        {
                            Id = 17,
                            Color = "#143f71",
                            CreatedDate = new DateTime(2022, 2, 1, 18, 23, 28, 973, DateTimeKind.Unspecified).AddTicks(1051),
                            Height = 90,
                            Status = 1,
                            Width = 42
                        },
                        new
                        {
                            Id = 18,
                            Color = "#7f3f0e",
                            CreatedDate = new DateTime(2022, 2, 28, 6, 52, 48, 575, DateTimeKind.Unspecified).AddTicks(9068),
                            Height = 119,
                            Status = 1,
                            Width = 87
                        },
                        new
                        {
                            Id = 19,
                            Color = "#7b741d",
                            CreatedDate = new DateTime(2022, 6, 9, 20, 13, 34, 928, DateTimeKind.Unspecified).AddTicks(4255),
                            Height = 122,
                            Status = 1,
                            Width = 166
                        },
                        new
                        {
                            Id = 20,
                            Color = "#121a51",
                            CreatedDate = new DateTime(2021, 10, 22, 16, 23, 59, 748, DateTimeKind.Unspecified).AddTicks(1392),
                            Height = 31,
                            Status = 1,
                            Width = 39
                        },
                        new
                        {
                            Id = 21,
                            Color = "#5a3c2c",
                            CreatedDate = new DateTime(2022, 8, 31, 23, 47, 57, 602, DateTimeKind.Unspecified).AddTicks(8434),
                            Height = 27,
                            Status = 1,
                            Width = 15
                        },
                        new
                        {
                            Id = 22,
                            Color = "#39137e",
                            CreatedDate = new DateTime(2022, 2, 3, 17, 38, 18, 628, DateTimeKind.Unspecified).AddTicks(3826),
                            Height = 23,
                            Status = 1,
                            Width = 84
                        },
                        new
                        {
                            Id = 23,
                            Color = "#30723d",
                            CreatedDate = new DateTime(2022, 7, 21, 11, 57, 40, 611, DateTimeKind.Unspecified).AddTicks(3664),
                            Height = 173,
                            Status = 1,
                            Width = 160
                        },
                        new
                        {
                            Id = 24,
                            Color = "#6c7b7e",
                            CreatedDate = new DateTime(2021, 6, 4, 4, 22, 13, 427, DateTimeKind.Unspecified).AddTicks(4912),
                            Height = 191,
                            Status = 1,
                            Width = 114
                        },
                        new
                        {
                            Id = 25,
                            Color = "#0b2b22",
                            CreatedDate = new DateTime(2022, 8, 25, 13, 32, 51, 822, DateTimeKind.Unspecified).AddTicks(3847),
                            Height = 38,
                            Status = 1,
                            Width = 110
                        },
                        new
                        {
                            Id = 26,
                            Color = "#1a6423",
                            CreatedDate = new DateTime(2021, 12, 18, 21, 13, 25, 30, DateTimeKind.Unspecified).AddTicks(7637),
                            Height = 45,
                            Status = 1,
                            Width = 132
                        },
                        new
                        {
                            Id = 27,
                            Color = "#583725",
                            CreatedDate = new DateTime(2022, 6, 14, 7, 10, 38, 165, DateTimeKind.Unspecified).AddTicks(8860),
                            Height = 128,
                            Status = 1,
                            Width = 191
                        },
                        new
                        {
                            Id = 28,
                            Color = "#102577",
                            CreatedDate = new DateTime(2022, 2, 8, 18, 31, 13, 526, DateTimeKind.Unspecified).AddTicks(3946),
                            Height = 140,
                            Status = 1,
                            Width = 78
                        },
                        new
                        {
                            Id = 29,
                            Color = "#721165",
                            CreatedDate = new DateTime(2022, 10, 30, 2, 58, 18, 355, DateTimeKind.Unspecified).AddTicks(988),
                            Height = 149,
                            Status = 1,
                            Width = 138
                        },
                        new
                        {
                            Id = 30,
                            Color = "#6f0d57",
                            CreatedDate = new DateTime(2022, 1, 24, 5, 27, 54, 738, DateTimeKind.Unspecified).AddTicks(529),
                            Height = 169,
                            Status = 1,
                            Width = 41
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserLanguage", b =>
                {
                    b.HasOne("NLayer.Core.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLayer.Core.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserProfile", b =>
                {
                    b.HasOne("NLayer.Core.Models.AppUser", "AppUser")
                        .WithOne("AppUserProfile")
                        .HasForeignKey("NLayer.Core.Models.AppUserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.HasOne("NLayer.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.HasOne("NLayer.Core.Models.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("NLayer.Core.Models.ProductFeature", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUser", b =>
                {
                    b.Navigation("AppUserProfile");
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Navigation("ProductFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
