// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayer.Repository;

#nullable disable

namespace NLayer.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221207212354_NewMigs12")]
    partial class NewMigs12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NLayer.Core.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivationCode = new Guid("42399926-e6fb-4ad8-9c30-1aaf89526a8b"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 5, 31, 3, 34, 32, 715, DateTimeKind.Unspecified).AddTicks(9946),
                            Status = 1,
                            UserName = "Aron37"
                        },
                        new
                        {
                            Id = 2,
                            ActivationCode = new Guid("368cda2b-d95f-4bb3-904a-26931175e02f"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 4, 5, 4, 2, 53, 276, DateTimeKind.Unspecified).AddTicks(3883),
                            Status = 1,
                            UserName = "Katelyn20"
                        },
                        new
                        {
                            Id = 3,
                            ActivationCode = new Guid("b9ec518f-8ad4-4690-885d-06cad27d238a"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 3, 14, 18, 19, 9, 59, DateTimeKind.Unspecified).AddTicks(3025),
                            Status = 1,
                            UserName = "Delbert25"
                        },
                        new
                        {
                            Id = 4,
                            ActivationCode = new Guid("32b2c8b5-2ab4-4d5e-9fba-8079d369ee52"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 11, 19, 9, 44, 12, 978, DateTimeKind.Unspecified).AddTicks(5036),
                            Status = 1,
                            UserName = "Raheem33"
                        },
                        new
                        {
                            Id = 5,
                            ActivationCode = new Guid("023fa736-dde9-479b-ac10-c7bf45afffa0"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 3, 24, 20, 52, 9, 312, DateTimeKind.Unspecified).AddTicks(9217),
                            Status = 1,
                            UserName = "Allison_Hermann17"
                        },
                        new
                        {
                            Id = 6,
                            ActivationCode = new Guid("f326d1ef-36d9-42d8-a0ae-0023a4f80aa6"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 10, 8, 5, 25, 19, 352, DateTimeKind.Unspecified).AddTicks(134),
                            Status = 1,
                            UserName = "Abraham.Nikolaus"
                        },
                        new
                        {
                            Id = 7,
                            ActivationCode = new Guid("856aedbc-04f9-4aca-8aca-42c5e01c942a"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 7, 11, 5, 52, 48, 688, DateTimeKind.Unspecified).AddTicks(2248),
                            Status = 1,
                            UserName = "Ramon87"
                        },
                        new
                        {
                            Id = 8,
                            ActivationCode = new Guid("6db1c4f2-12f0-4931-b024-e2b56e901364"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 5, 17, 0, 30, 57, 69, DateTimeKind.Unspecified).AddTicks(6408),
                            Status = 1,
                            UserName = "Alia.Lehner"
                        },
                        new
                        {
                            Id = 9,
                            ActivationCode = new Guid("8fe83c14-2492-47c5-8057-d64a8b186903"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 10, 8, 18, 45, 32, 618, DateTimeKind.Unspecified).AddTicks(8978),
                            Status = 1,
                            UserName = "Harmon_Koch83"
                        },
                        new
                        {
                            Id = 10,
                            ActivationCode = new Guid("d06c6bcf-e3f6-47bb-b5d0-d416bfff978a"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 1, 24, 13, 17, 15, 983, DateTimeKind.Unspecified).AddTicks(168),
                            Status = 1,
                            UserName = "Serena.White34"
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserLanguage", b =>
                {
                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GivenBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("LanguageID", "AppUserID");

                    b.HasIndex("AppUserID");

                    b.ToTable("AppUsersLanguages");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("AppUserProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 5, 28, 21, 22, 31, 777, DateTimeKind.Unspecified).AddTicks(1751),
                            FirstName = "Phyllis",
                            LastName = "Ullrich",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 12, 29, 4, 7, 40, 111, DateTimeKind.Unspecified).AddTicks(8812),
                            FirstName = "Allison",
                            LastName = "VonRueden",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 7, 20, 7, 43, 18, 330, DateTimeKind.Unspecified).AddTicks(3195),
                            FirstName = "Eric",
                            LastName = "Littel",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 5, 23, 8, 57, 59, 496, DateTimeKind.Unspecified).AddTicks(6558),
                            FirstName = "Alex",
                            LastName = "Corkery",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 11, 26, 9, 22, 4, 590, DateTimeKind.Unspecified).AddTicks(3447),
                            FirstName = "Jeremy",
                            LastName = "Goldner",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 3, 14, 1, 20, 43, 17, DateTimeKind.Unspecified).AddTicks(1397),
                            FirstName = "Lillian",
                            LastName = "Crooks",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 9, 24, 13, 16, 21, 494, DateTimeKind.Unspecified).AddTicks(9766),
                            FirstName = "Lynette",
                            LastName = "Veum",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 1, 30, 1, 4, 59, 597, DateTimeKind.Unspecified).AddTicks(8479),
                            FirstName = "Tabitha",
                            LastName = "VonRueden",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 11, 10, 7, 16, 12, 467, DateTimeKind.Unspecified).AddTicks(7627),
                            FirstName = "Rosalie",
                            LastName = "Braun",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2022, 11, 19, 7, 26, 53, 133, DateTimeKind.Unspecified).AddTicks(9569),
                            FirstName = "Shawna",
                            LastName = "Cremin",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 7, 23, 9, 25, 21, 228, DateTimeKind.Unspecified).AddTicks(1737),
                            Name = "Music",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 5, 13, 8, 26, 18, 406, DateTimeKind.Unspecified).AddTicks(7972),
                            Name = "Electronics",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 4, 14, 21, 10, 30, 844, DateTimeKind.Unspecified).AddTicks(8929),
                            Name = "Sports",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 4, 1, 23, 29, 43, 791, DateTimeKind.Unspecified).AddTicks(7908),
                            Name = "Beauty",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 3, 5, 15, 54, 15, 214, DateTimeKind.Unspecified).AddTicks(9862),
                            Name = "Electronics",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 4, 20, 8, 26, 45, 915, DateTimeKind.Unspecified).AddTicks(5857),
                            Name = "Tools",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 7, 9, 19, 11, 54, 524, DateTimeKind.Unspecified).AddTicks(2210),
                            Name = "Shoes",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2021, 6, 8, 3, 21, 42, 634, DateTimeKind.Unspecified).AddTicks(9251),
                            Name = "Kids",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 2, 12, 18, 10, 11, 482, DateTimeKind.Unspecified).AddTicks(5649),
                            Name = "Grocery",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2021, 6, 30, 2, 12, 22, 423, DateTimeKind.Unspecified).AddTicks(1035),
                            Name = "Grocery",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 12, 8, 0, 23, 54, 742, DateTimeKind.Local).AddTicks(8326),
                            LanguageName = "Turkish",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 12, 8, 0, 23, 54, 742, DateTimeKind.Local).AddTicks(8330),
                            LanguageName = "German",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 12, 8, 0, 23, 54, 742, DateTimeKind.Local).AddTicks(8331),
                            LanguageName = "English",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 12, 8, 0, 23, 54, 742, DateTimeKind.Local).AddTicks(8332),
                            LanguageName = "Korean",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 12, 8, 0, 23, 54, 742, DateTimeKind.Local).AddTicks(8333),
                            LanguageName = "Finnish",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 12, 8, 0, 23, 54, 742, DateTimeKind.Local).AddTicks(8335),
                            LanguageName = "French",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 12, 8, 0, 23, 54, 742, DateTimeKind.Local).AddTicks(8336),
                            LanguageName = "Czech",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 12, 8, 0, 23, 54, 742, DateTimeKind.Local).AddTicks(8337),
                            LanguageName = "Spanish ",
                            Level = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Urunler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 6, 22, 10, 49, 45, 91, DateTimeKind.Unspecified).AddTicks(3352),
                            Name = "Practical Wooden Hat",
                            Price = 49m,
                            Status = 1,
                            Stock = 151
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2022, 4, 13, 2, 21, 54, 274, DateTimeKind.Unspecified).AddTicks(3428),
                            Name = "Handmade Fresh Gloves",
                            Price = 52m,
                            Status = 1,
                            Stock = 24
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 9, 4, 20, 54, 48, 462, DateTimeKind.Unspecified).AddTicks(8781),
                            Name = "Generic Soft Shirt",
                            Price = 54m,
                            Status = 1,
                            Stock = 125
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 21, 18, 1, 39, 992, DateTimeKind.Unspecified).AddTicks(2094),
                            Name = "Handcrafted Metal Gloves",
                            Price = 53m,
                            Status = 1,
                            Stock = 89
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2021, 11, 22, 1, 38, 9, 821, DateTimeKind.Unspecified).AddTicks(2248),
                            Name = "Awesome Plastic Sausages",
                            Price = 52m,
                            Status = 1,
                            Stock = 112
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2021, 7, 21, 10, 4, 31, 337, DateTimeKind.Unspecified).AddTicks(6233),
                            Name = "Incredible Concrete Gloves",
                            Price = 55m,
                            Status = 1,
                            Stock = 152
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 6, 9, 20, 56, 22, 584, DateTimeKind.Unspecified).AddTicks(9376),
                            Name = "Incredible Soft Bacon",
                            Price = 51m,
                            Status = 1,
                            Stock = 77
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 3, 23, 15, 29, 11, 965, DateTimeKind.Unspecified).AddTicks(9811),
                            Name = "Practical Cotton Salad",
                            Price = 54m,
                            Status = 1,
                            Stock = 123
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2021, 4, 23, 9, 5, 19, 797, DateTimeKind.Unspecified).AddTicks(5343),
                            Name = "Sleek Metal Fish",
                            Price = 53m,
                            Status = 1,
                            Stock = 119
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 4, 10, 11, 42, 17, 229, DateTimeKind.Unspecified).AddTicks(3040),
                            Name = "Practical Concrete Keyboard",
                            Price = 52m,
                            Status = 1,
                            Stock = 163
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2021, 11, 16, 10, 22, 9, 529, DateTimeKind.Unspecified).AddTicks(8874),
                            Name = "Incredible Frozen Bacon",
                            Price = 52m,
                            Status = 1,
                            Stock = 107
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 7, 27, 4, 18, 21, 965, DateTimeKind.Unspecified).AddTicks(6732),
                            Name = "Ergonomic Soft Towels",
                            Price = 53m,
                            Status = 1,
                            Stock = 55
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 7, 24, 17, 47, 50, 755, DateTimeKind.Unspecified).AddTicks(8351),
                            Name = "Practical Concrete Car",
                            Price = 53m,
                            Status = 1,
                            Stock = 47
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 9, 18, 10, 25, 29, 359, DateTimeKind.Unspecified).AddTicks(6033),
                            Name = "Practical Fresh Sausages",
                            Price = 51m,
                            Status = 1,
                            Stock = 190
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 6, 6, 8, 9, 38, 403, DateTimeKind.Unspecified).AddTicks(9867),
                            Name = "Handcrafted Wooden Bike",
                            Price = 53m,
                            Status = 1,
                            Stock = 34
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 9, 16, 10, 29, 45, 204, DateTimeKind.Unspecified).AddTicks(6509),
                            Name = "Incredible Concrete Fish",
                            Price = 57m,
                            Status = 1,
                            Stock = 3
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 3, 18, 12, 0, 32, 159, DateTimeKind.Unspecified).AddTicks(5890),
                            Name = "Tasty Granite Gloves",
                            Price = 54m,
                            Status = 1,
                            Stock = 107
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2021, 6, 2, 5, 11, 37, 184, DateTimeKind.Unspecified).AddTicks(6016),
                            Name = "Ergonomic Concrete Keyboard",
                            Price = 53m,
                            Status = 1,
                            Stock = 197
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 10, 11, 3, 22, 33, 232, DateTimeKind.Unspecified).AddTicks(5862),
                            Name = "Fantastic Plastic Table",
                            Price = 52m,
                            Status = 1,
                            Stock = 35
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2022, 3, 17, 21, 56, 14, 578, DateTimeKind.Unspecified).AddTicks(7040),
                            Name = "Handcrafted Granite Mouse",
                            Price = 50m,
                            Status = 1,
                            Stock = 36
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 5, 22, 8, 51, 19, 955, DateTimeKind.Unspecified).AddTicks(8532),
                            Name = "Small Soft Gloves",
                            Price = 54m,
                            Status = 1,
                            Stock = 28
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 4, 18, 3, 37, 39, 54, DateTimeKind.Unspecified).AddTicks(3390),
                            Name = "Refined Soft Keyboard",
                            Price = 50m,
                            Status = 1,
                            Stock = 59
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2021, 5, 1, 16, 56, 54, 485, DateTimeKind.Unspecified).AddTicks(2357),
                            Name = "Licensed Concrete Keyboard",
                            Price = 54m,
                            Status = 1,
                            Stock = 116
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 9, 30, 7, 7, 20, 398, DateTimeKind.Unspecified).AddTicks(7029),
                            Name = "Fantastic Soft Soap",
                            Price = 51m,
                            Status = 1,
                            Stock = 7
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 5, 9, 11, 44, 20, 303, DateTimeKind.Unspecified).AddTicks(2776),
                            Name = "Tasty Steel Chicken",
                            Price = 57m,
                            Status = 1,
                            Stock = 71
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2021, 4, 23, 22, 49, 1, 32, DateTimeKind.Unspecified).AddTicks(6761),
                            Name = "Sleek Frozen Soap",
                            Price = 53m,
                            Status = 1,
                            Stock = 16
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 10, 8, 3, 1, 10, 624, DateTimeKind.Unspecified).AddTicks(7429),
                            Name = "Handmade Cotton Chicken",
                            Price = 53m,
                            Status = 1,
                            Stock = 38
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 1, 2, 16, 23, 53, 432, DateTimeKind.Unspecified).AddTicks(7626),
                            Name = "Handmade Fresh Sausages",
                            Price = 50m,
                            Status = 1,
                            Stock = 26
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 3, 18, 3, 6, 17, 903, DateTimeKind.Unspecified).AddTicks(7926),
                            Name = "Handcrafted Soft Towels",
                            Price = 53m,
                            Status = 1,
                            Stock = 119
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 8, 4, 13, 11, 14, 135, DateTimeKind.Unspecified).AddTicks(4283),
                            Name = "Licensed Concrete Shirt",
                            Price = 51m,
                            Status = 1,
                            Stock = 107
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UrunOzellikleri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#67501a",
                            CreatedDate = new DateTime(2022, 6, 17, 12, 14, 32, 626, DateTimeKind.Unspecified).AddTicks(8435),
                            Height = 105,
                            Status = 1,
                            Width = 163
                        },
                        new
                        {
                            Id = 2,
                            Color = "#484307",
                            CreatedDate = new DateTime(2022, 3, 7, 8, 25, 31, 864, DateTimeKind.Unspecified).AddTicks(2793),
                            Height = 106,
                            Status = 1,
                            Width = 5
                        },
                        new
                        {
                            Id = 3,
                            Color = "#320e2c",
                            CreatedDate = new DateTime(2022, 9, 6, 1, 26, 25, 160, DateTimeKind.Unspecified).AddTicks(4085),
                            Height = 156,
                            Status = 1,
                            Width = 185
                        },
                        new
                        {
                            Id = 4,
                            Color = "#15000a",
                            CreatedDate = new DateTime(2021, 12, 22, 17, 13, 19, 825, DateTimeKind.Unspecified).AddTicks(1155),
                            Height = 109,
                            Status = 1,
                            Width = 191
                        },
                        new
                        {
                            Id = 5,
                            Color = "#742344",
                            CreatedDate = new DateTime(2022, 4, 27, 21, 15, 48, 610, DateTimeKind.Unspecified).AddTicks(2358),
                            Height = 59,
                            Status = 1,
                            Width = 133
                        },
                        new
                        {
                            Id = 6,
                            Color = "#595249",
                            CreatedDate = new DateTime(2022, 8, 6, 13, 44, 13, 632, DateTimeKind.Unspecified).AddTicks(101),
                            Height = 86,
                            Status = 1,
                            Width = 141
                        },
                        new
                        {
                            Id = 7,
                            Color = "#486e3b",
                            CreatedDate = new DateTime(2021, 11, 21, 19, 23, 51, 498, DateTimeKind.Unspecified).AddTicks(2631),
                            Height = 183,
                            Status = 1,
                            Width = 17
                        },
                        new
                        {
                            Id = 8,
                            Color = "#77143d",
                            CreatedDate = new DateTime(2021, 6, 2, 17, 46, 3, 781, DateTimeKind.Unspecified).AddTicks(496),
                            Height = 65,
                            Status = 1,
                            Width = 168
                        },
                        new
                        {
                            Id = 9,
                            Color = "#160357",
                            CreatedDate = new DateTime(2022, 4, 24, 11, 45, 46, 773, DateTimeKind.Unspecified).AddTicks(6910),
                            Height = 14,
                            Status = 1,
                            Width = 134
                        },
                        new
                        {
                            Id = 10,
                            Color = "#720b70",
                            CreatedDate = new DateTime(2022, 6, 30, 2, 3, 34, 457, DateTimeKind.Unspecified).AddTicks(2662),
                            Height = 160,
                            Status = 1,
                            Width = 83
                        },
                        new
                        {
                            Id = 11,
                            Color = "#08300e",
                            CreatedDate = new DateTime(2021, 6, 11, 4, 4, 5, 629, DateTimeKind.Unspecified).AddTicks(6948),
                            Height = 149,
                            Status = 1,
                            Width = 123
                        },
                        new
                        {
                            Id = 12,
                            Color = "#511b6a",
                            CreatedDate = new DateTime(2021, 8, 2, 13, 14, 58, 974, DateTimeKind.Unspecified).AddTicks(9050),
                            Height = 4,
                            Status = 1,
                            Width = 166
                        },
                        new
                        {
                            Id = 13,
                            Color = "#673b3d",
                            CreatedDate = new DateTime(2021, 11, 22, 14, 17, 0, 68, DateTimeKind.Unspecified).AddTicks(7038),
                            Height = 86,
                            Status = 1,
                            Width = 199
                        },
                        new
                        {
                            Id = 14,
                            Color = "#24656b",
                            CreatedDate = new DateTime(2021, 5, 6, 2, 46, 37, 645, DateTimeKind.Unspecified).AddTicks(2263),
                            Height = 137,
                            Status = 1,
                            Width = 10
                        },
                        new
                        {
                            Id = 15,
                            Color = "#524f75",
                            CreatedDate = new DateTime(2022, 4, 26, 3, 45, 51, 803, DateTimeKind.Unspecified).AddTicks(7804),
                            Height = 22,
                            Status = 1,
                            Width = 138
                        },
                        new
                        {
                            Id = 16,
                            Color = "#775900",
                            CreatedDate = new DateTime(2022, 1, 4, 22, 49, 26, 198, DateTimeKind.Unspecified).AddTicks(7980),
                            Height = 110,
                            Status = 1,
                            Width = 186
                        },
                        new
                        {
                            Id = 17,
                            Color = "#681d7f",
                            CreatedDate = new DateTime(2021, 12, 10, 8, 37, 20, 160, DateTimeKind.Unspecified).AddTicks(8811),
                            Height = 96,
                            Status = 1,
                            Width = 99
                        },
                        new
                        {
                            Id = 18,
                            Color = "#563d22",
                            CreatedDate = new DateTime(2021, 3, 19, 6, 59, 20, 651, DateTimeKind.Unspecified).AddTicks(5058),
                            Height = 145,
                            Status = 1,
                            Width = 1
                        },
                        new
                        {
                            Id = 19,
                            Color = "#4a4e2a",
                            CreatedDate = new DateTime(2021, 8, 12, 17, 15, 50, 713, DateTimeKind.Unspecified).AddTicks(6373),
                            Height = 97,
                            Status = 1,
                            Width = 35
                        },
                        new
                        {
                            Id = 20,
                            Color = "#59785f",
                            CreatedDate = new DateTime(2021, 8, 21, 14, 45, 38, 723, DateTimeKind.Unspecified).AddTicks(8107),
                            Height = 60,
                            Status = 1,
                            Width = 57
                        },
                        new
                        {
                            Id = 21,
                            Color = "#5c323e",
                            CreatedDate = new DateTime(2022, 10, 5, 18, 39, 23, 758, DateTimeKind.Unspecified).AddTicks(4760),
                            Height = 134,
                            Status = 1,
                            Width = 31
                        },
                        new
                        {
                            Id = 22,
                            Color = "#377772",
                            CreatedDate = new DateTime(2021, 8, 1, 4, 3, 36, 533, DateTimeKind.Unspecified).AddTicks(1984),
                            Height = 118,
                            Status = 1,
                            Width = 151
                        },
                        new
                        {
                            Id = 23,
                            Color = "#6e394e",
                            CreatedDate = new DateTime(2021, 9, 22, 3, 5, 37, 940, DateTimeKind.Unspecified).AddTicks(4395),
                            Height = 15,
                            Status = 1,
                            Width = 49
                        },
                        new
                        {
                            Id = 24,
                            Color = "#175503",
                            CreatedDate = new DateTime(2022, 11, 3, 9, 53, 45, 73, DateTimeKind.Unspecified).AddTicks(1978),
                            Height = 165,
                            Status = 1,
                            Width = 22
                        },
                        new
                        {
                            Id = 25,
                            Color = "#192e1e",
                            CreatedDate = new DateTime(2021, 6, 10, 0, 19, 16, 60, DateTimeKind.Unspecified).AddTicks(8080),
                            Height = 26,
                            Status = 1,
                            Width = 164
                        },
                        new
                        {
                            Id = 26,
                            Color = "#400940",
                            CreatedDate = new DateTime(2021, 11, 15, 12, 21, 16, 879, DateTimeKind.Unspecified).AddTicks(8939),
                            Height = 43,
                            Status = 1,
                            Width = 118
                        },
                        new
                        {
                            Id = 27,
                            Color = "#796326",
                            CreatedDate = new DateTime(2022, 9, 2, 12, 22, 8, 564, DateTimeKind.Unspecified).AddTicks(5617),
                            Height = 140,
                            Status = 1,
                            Width = 22
                        },
                        new
                        {
                            Id = 28,
                            Color = "#13652c",
                            CreatedDate = new DateTime(2022, 11, 5, 22, 31, 2, 122, DateTimeKind.Unspecified).AddTicks(4988),
                            Height = 94,
                            Status = 1,
                            Width = 149
                        },
                        new
                        {
                            Id = 29,
                            Color = "#423024",
                            CreatedDate = new DateTime(2021, 7, 14, 7, 35, 53, 754, DateTimeKind.Unspecified).AddTicks(7670),
                            Height = 14,
                            Status = 1,
                            Width = 183
                        },
                        new
                        {
                            Id = 30,
                            Color = "#57775c",
                            CreatedDate = new DateTime(2021, 6, 23, 4, 36, 56, 195, DateTimeKind.Unspecified).AddTicks(7003),
                            Height = 1,
                            Status = 1,
                            Width = 107
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserLanguage", b =>
                {
                    b.HasOne("NLayer.Core.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLayer.Core.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserProfile", b =>
                {
                    b.HasOne("NLayer.Core.Models.AppUser", "AppUser")
                        .WithOne("AppUserProfile")
                        .HasForeignKey("NLayer.Core.Models.AppUserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.HasOne("NLayer.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.HasOne("NLayer.Core.Models.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("NLayer.Core.Models.ProductFeature", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUser", b =>
                {
                    b.Navigation("AppUserProfile");
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Navigation("ProductFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
