// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayer.Repository;

#nullable disable

namespace NLayer.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220714121221_bogus")]
    partial class bogus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 11, 10, 14, 26, 4, 316, DateTimeKind.Unspecified).AddTicks(6606),
                            Name = "Games",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 12, 24, 10, 17, 14, 49, DateTimeKind.Unspecified).AddTicks(7397),
                            Name = "Toys",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 5, 14, 19, 37, 27, 558, DateTimeKind.Unspecified).AddTicks(3363),
                            Name = "Toys",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 5, 15, 9, 57, 45, 335, DateTimeKind.Unspecified).AddTicks(2357),
                            Name = "Movies",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 1, 30, 17, 59, 41, 342, DateTimeKind.Unspecified).AddTicks(1877),
                            Name = "Industrial",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 1, 2, 13, 14, 36, 683, DateTimeKind.Unspecified).AddTicks(9574),
                            Name = "Baby",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2021, 4, 11, 1, 46, 15, 317, DateTimeKind.Unspecified).AddTicks(5726),
                            Name = "Health",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2021, 3, 19, 18, 45, 11, 607, DateTimeKind.Unspecified).AddTicks(8330),
                            Name = "Jewelery",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2021, 5, 24, 2, 47, 22, 129, DateTimeKind.Unspecified).AddTicks(4352),
                            Name = "Kids",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2021, 8, 22, 9, 33, 36, 944, DateTimeKind.Unspecified).AddTicks(9464),
                            Name = "Outdoors",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Urunler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 10, 29, 23, 24, 52, 530, DateTimeKind.Unspecified).AddTicks(3019),
                            Name = "Gorgeous Plastic Chicken",
                            Price = 53m,
                            Status = 1,
                            Stock = 79
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 7, 29, 23, 2, 30, 324, DateTimeKind.Unspecified).AddTicks(4223),
                            Name = "Incredible Rubber Towels",
                            Price = 49m,
                            Status = 1,
                            Stock = 146
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 9, 28, 0, 27, 21, 625, DateTimeKind.Unspecified).AddTicks(116),
                            Name = "Fantastic Frozen Keyboard",
                            Price = 52m,
                            Status = 1,
                            Stock = 63
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2021, 5, 26, 15, 22, 17, 672, DateTimeKind.Unspecified).AddTicks(7488),
                            Name = "Tasty Rubber Chair",
                            Price = 49m,
                            Status = 1,
                            Stock = 54
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2021, 9, 18, 6, 36, 3, 460, DateTimeKind.Unspecified).AddTicks(1850),
                            Name = "Refined Soft Table",
                            Price = 49m,
                            Status = 1,
                            Stock = 9
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 8, 6, 8, 49, 34, 720, DateTimeKind.Unspecified).AddTicks(7373),
                            Name = "Incredible Fresh Keyboard",
                            Price = 56m,
                            Status = 1,
                            Stock = 92
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 4, 20, 22, 12, 37, 266, DateTimeKind.Unspecified).AddTicks(4962),
                            Name = "Handmade Granite Sausages",
                            Price = 51m,
                            Status = 1,
                            Stock = 190
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 6, 20, 7, 8, 30, 795, DateTimeKind.Unspecified).AddTicks(8450),
                            Name = "Fantastic Concrete Fish",
                            Price = 55m,
                            Status = 1,
                            Stock = 190
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 5, 8, 11, 36, 39, 410, DateTimeKind.Unspecified).AddTicks(7116),
                            Name = "Generic Metal Bike",
                            Price = 57m,
                            Status = 1,
                            Stock = 148
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 7, 3, 15, 31, 0, 610, DateTimeKind.Unspecified).AddTicks(6066),
                            Name = "Gorgeous Frozen Bacon",
                            Price = 51m,
                            Status = 1,
                            Stock = 12
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 10, 17, 35, 43, 233, DateTimeKind.Unspecified).AddTicks(2162),
                            Name = "Handcrafted Wooden Table",
                            Price = 57m,
                            Status = 1,
                            Stock = 80
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 4, 11, 6, 47, 33, 989, DateTimeKind.Unspecified).AddTicks(7543),
                            Name = "Handmade Soft Pizza",
                            Price = 52m,
                            Status = 1,
                            Stock = 51
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2022, 5, 17, 0, 22, 14, 374, DateTimeKind.Unspecified).AddTicks(2691),
                            Name = "Tasty Granite Fish",
                            Price = 52m,
                            Status = 1,
                            Stock = 58
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2022, 4, 27, 16, 12, 39, 501, DateTimeKind.Unspecified).AddTicks(4406),
                            Name = "Practical Plastic Bacon",
                            Price = 56m,
                            Status = 1,
                            Stock = 188
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 3, 29, 0, 20, 50, 413, DateTimeKind.Unspecified).AddTicks(9338),
                            Name = "Handcrafted Soft Pants",
                            Price = 50m,
                            Status = 1,
                            Stock = 137
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 4, 9, 9, 39, 59, 461, DateTimeKind.Unspecified).AddTicks(1684),
                            Name = "Practical Wooden Fish",
                            Price = 51m,
                            Status = 1,
                            Stock = 7
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2021, 9, 10, 13, 58, 5, 23, DateTimeKind.Unspecified).AddTicks(5055),
                            Name = "Fantastic Metal Fish",
                            Price = 50m,
                            Status = 1,
                            Stock = 84
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2022, 3, 18, 23, 40, 52, 891, DateTimeKind.Unspecified).AddTicks(9957),
                            Name = "Fantastic Rubber Salad",
                            Price = 56m,
                            Status = 1,
                            Stock = 179
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 5, 9, 19, 51, 5, 547, DateTimeKind.Unspecified).AddTicks(690),
                            Name = "Practical Metal Cheese",
                            Price = 53m,
                            Status = 1,
                            Stock = 63
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 7, 18, 17, 10, 33, 272, DateTimeKind.Unspecified).AddTicks(7242),
                            Name = "Tasty Cotton Pizza",
                            Price = 57m,
                            Status = 1,
                            Stock = 124
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 9, 15, 12, 30, 19, 721, DateTimeKind.Unspecified).AddTicks(5351),
                            Name = "Incredible Steel Keyboard",
                            Price = 49m,
                            Status = 1,
                            Stock = 151
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 5, 6, 14, 36, 53, 348, DateTimeKind.Unspecified).AddTicks(4784),
                            Name = "Awesome Granite Bike",
                            Price = 55m,
                            Status = 1,
                            Stock = 13
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2021, 10, 2, 1, 47, 6, 87, DateTimeKind.Unspecified).AddTicks(1501),
                            Name = "Ergonomic Steel Bike",
                            Price = 49m,
                            Status = 1,
                            Stock = 175
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 11, 25, 12, 36, 29, 127, DateTimeKind.Unspecified).AddTicks(8413),
                            Name = "Incredible Rubber Chicken",
                            Price = 54m,
                            Status = 1,
                            Stock = 117
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 2, 27, 10, 32, 22, 740, DateTimeKind.Unspecified).AddTicks(3813),
                            Name = "Small Metal Gloves",
                            Price = 49m,
                            Status = 1,
                            Stock = 141
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 2, 0, 30, 57, 62, DateTimeKind.Unspecified).AddTicks(4022),
                            Name = "Rustic Frozen Chicken",
                            Price = 50m,
                            Status = 1,
                            Stock = 95
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 5, 2, 22, 10, 57, 433, DateTimeKind.Unspecified).AddTicks(9974),
                            Name = "Small Wooden Chair",
                            Price = 54m,
                            Status = 1,
                            Stock = 191
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 10, 11, 8, 40, 0, 959, DateTimeKind.Unspecified).AddTicks(9467),
                            Name = "Tasty Metal Pizza",
                            Price = 54m,
                            Status = 1,
                            Stock = 182
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 7, 21, 4, 8, 52, 961, DateTimeKind.Unspecified).AddTicks(4833),
                            Name = "Practical Concrete Pants",
                            Price = 50m,
                            Status = 1,
                            Stock = 86
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2021, 10, 10, 7, 20, 41, 715, DateTimeKind.Unspecified).AddTicks(2841),
                            Name = "Small Steel Chips",
                            Price = 53m,
                            Status = 1,
                            Stock = 139
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UrunOzellikleri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#4b262d",
                            CreatedDate = new DateTime(2021, 4, 28, 8, 48, 6, 544, DateTimeKind.Unspecified).AddTicks(319),
                            Height = 139,
                            Status = 1,
                            Width = 154
                        },
                        new
                        {
                            Id = 2,
                            Color = "#732d23",
                            CreatedDate = new DateTime(2022, 1, 13, 20, 20, 58, 124, DateTimeKind.Unspecified).AddTicks(452),
                            Height = 162,
                            Status = 1,
                            Width = 103
                        },
                        new
                        {
                            Id = 3,
                            Color = "#3f4b7c",
                            CreatedDate = new DateTime(2021, 3, 22, 8, 27, 54, 619, DateTimeKind.Unspecified).AddTicks(7037),
                            Height = 77,
                            Status = 1,
                            Width = 97
                        },
                        new
                        {
                            Id = 4,
                            Color = "#5b6c2f",
                            CreatedDate = new DateTime(2022, 6, 25, 7, 31, 28, 96, DateTimeKind.Unspecified).AddTicks(3453),
                            Height = 190,
                            Status = 1,
                            Width = 109
                        },
                        new
                        {
                            Id = 5,
                            Color = "#767c59",
                            CreatedDate = new DateTime(2021, 5, 11, 12, 45, 0, 611, DateTimeKind.Unspecified).AddTicks(1016),
                            Height = 170,
                            Status = 1,
                            Width = 64
                        },
                        new
                        {
                            Id = 6,
                            Color = "#604a4f",
                            CreatedDate = new DateTime(2022, 1, 28, 23, 19, 47, 144, DateTimeKind.Unspecified).AddTicks(5366),
                            Height = 33,
                            Status = 1,
                            Width = 154
                        },
                        new
                        {
                            Id = 7,
                            Color = "#555308",
                            CreatedDate = new DateTime(2022, 6, 28, 9, 38, 16, 619, DateTimeKind.Unspecified).AddTicks(3029),
                            Height = 200,
                            Status = 1,
                            Width = 19
                        },
                        new
                        {
                            Id = 8,
                            Color = "#336d2a",
                            CreatedDate = new DateTime(2021, 10, 29, 5, 3, 32, 283, DateTimeKind.Unspecified).AddTicks(5048),
                            Height = 177,
                            Status = 1,
                            Width = 30
                        },
                        new
                        {
                            Id = 9,
                            Color = "#640f39",
                            CreatedDate = new DateTime(2021, 7, 3, 8, 42, 42, 393, DateTimeKind.Unspecified).AddTicks(6345),
                            Height = 68,
                            Status = 1,
                            Width = 44
                        },
                        new
                        {
                            Id = 10,
                            Color = "#5d144d",
                            CreatedDate = new DateTime(2021, 8, 7, 21, 13, 41, 15, DateTimeKind.Unspecified).AddTicks(3247),
                            Height = 19,
                            Status = 1,
                            Width = 167
                        },
                        new
                        {
                            Id = 11,
                            Color = "#5b707f",
                            CreatedDate = new DateTime(2022, 6, 14, 3, 30, 31, 161, DateTimeKind.Unspecified).AddTicks(9504),
                            Height = 158,
                            Status = 1,
                            Width = 35
                        },
                        new
                        {
                            Id = 12,
                            Color = "#42385b",
                            CreatedDate = new DateTime(2022, 3, 12, 6, 50, 41, 425, DateTimeKind.Unspecified).AddTicks(5957),
                            Height = 167,
                            Status = 1,
                            Width = 108
                        },
                        new
                        {
                            Id = 13,
                            Color = "#4c3f2e",
                            CreatedDate = new DateTime(2021, 8, 15, 18, 50, 10, 291, DateTimeKind.Unspecified).AddTicks(6225),
                            Height = 107,
                            Status = 1,
                            Width = 103
                        },
                        new
                        {
                            Id = 14,
                            Color = "#736a4b",
                            CreatedDate = new DateTime(2021, 12, 15, 8, 9, 17, 738, DateTimeKind.Unspecified).AddTicks(2522),
                            Height = 125,
                            Status = 1,
                            Width = 43
                        },
                        new
                        {
                            Id = 15,
                            Color = "#4f6502",
                            CreatedDate = new DateTime(2021, 7, 7, 21, 53, 0, 183, DateTimeKind.Unspecified).AddTicks(1238),
                            Height = 152,
                            Status = 1,
                            Width = 182
                        },
                        new
                        {
                            Id = 16,
                            Color = "#5a277e",
                            CreatedDate = new DateTime(2021, 11, 2, 18, 21, 42, 369, DateTimeKind.Unspecified).AddTicks(4324),
                            Height = 176,
                            Status = 1,
                            Width = 158
                        },
                        new
                        {
                            Id = 17,
                            Color = "#621576",
                            CreatedDate = new DateTime(2022, 2, 5, 9, 15, 18, 443, DateTimeKind.Unspecified).AddTicks(4449),
                            Height = 97,
                            Status = 1,
                            Width = 175
                        },
                        new
                        {
                            Id = 18,
                            Color = "#35686d",
                            CreatedDate = new DateTime(2022, 4, 6, 6, 12, 56, 277, DateTimeKind.Unspecified).AddTicks(9045),
                            Height = 177,
                            Status = 1,
                            Width = 143
                        },
                        new
                        {
                            Id = 19,
                            Color = "#4e6654",
                            CreatedDate = new DateTime(2022, 4, 22, 15, 10, 19, 471, DateTimeKind.Unspecified).AddTicks(336),
                            Height = 11,
                            Status = 1,
                            Width = 168
                        },
                        new
                        {
                            Id = 20,
                            Color = "#2c3964",
                            CreatedDate = new DateTime(2021, 4, 18, 0, 17, 36, 335, DateTimeKind.Unspecified).AddTicks(3375),
                            Height = 49,
                            Status = 1,
                            Width = 187
                        },
                        new
                        {
                            Id = 21,
                            Color = "#567226",
                            CreatedDate = new DateTime(2021, 10, 14, 6, 50, 3, 719, DateTimeKind.Unspecified).AddTicks(3243),
                            Height = 34,
                            Status = 1,
                            Width = 183
                        },
                        new
                        {
                            Id = 22,
                            Color = "#7f5a04",
                            CreatedDate = new DateTime(2021, 10, 1, 10, 26, 15, 514, DateTimeKind.Unspecified).AddTicks(4978),
                            Height = 58,
                            Status = 1,
                            Width = 184
                        },
                        new
                        {
                            Id = 23,
                            Color = "#80375d",
                            CreatedDate = new DateTime(2021, 10, 31, 2, 0, 27, 69, DateTimeKind.Unspecified).AddTicks(8704),
                            Height = 37,
                            Status = 1,
                            Width = 167
                        },
                        new
                        {
                            Id = 24,
                            Color = "#29787e",
                            CreatedDate = new DateTime(2021, 11, 10, 15, 2, 6, 411, DateTimeKind.Unspecified).AddTicks(8960),
                            Height = 128,
                            Status = 1,
                            Width = 17
                        },
                        new
                        {
                            Id = 25,
                            Color = "#3f6d75",
                            CreatedDate = new DateTime(2021, 9, 15, 8, 44, 30, 347, DateTimeKind.Unspecified).AddTicks(7104),
                            Height = 135,
                            Status = 1,
                            Width = 58
                        },
                        new
                        {
                            Id = 26,
                            Color = "#716258",
                            CreatedDate = new DateTime(2022, 6, 25, 20, 10, 32, 169, DateTimeKind.Unspecified).AddTicks(5184),
                            Height = 161,
                            Status = 1,
                            Width = 94
                        },
                        new
                        {
                            Id = 27,
                            Color = "#607748",
                            CreatedDate = new DateTime(2021, 7, 10, 20, 4, 57, 125, DateTimeKind.Unspecified).AddTicks(5432),
                            Height = 26,
                            Status = 1,
                            Width = 191
                        },
                        new
                        {
                            Id = 28,
                            Color = "#56110d",
                            CreatedDate = new DateTime(2021, 6, 23, 5, 48, 48, 184, DateTimeKind.Unspecified).AddTicks(8850),
                            Height = 197,
                            Status = 1,
                            Width = 37
                        },
                        new
                        {
                            Id = 29,
                            Color = "#6f0211",
                            CreatedDate = new DateTime(2021, 5, 27, 19, 20, 11, 533, DateTimeKind.Unspecified).AddTicks(1088),
                            Height = 137,
                            Status = 1,
                            Width = 167
                        },
                        new
                        {
                            Id = 30,
                            Color = "#543d72",
                            CreatedDate = new DateTime(2021, 9, 10, 22, 58, 49, 198, DateTimeKind.Unspecified).AddTicks(5394),
                            Height = 79,
                            Status = 1,
                            Width = 88
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.HasOne("NLayer.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.HasOne("NLayer.Core.Models.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("NLayer.Core.Models.ProductFeature", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Navigation("ProductFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
