// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayer.Repository;

#nullable disable

namespace NLayer.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221207212106_NewMigs")]
    partial class NewMigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NLayer.Core.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivationCode = new Guid("9349893c-3159-4af5-ba50-029faee4b154"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 8, 22, 11, 29, 43, 828, DateTimeKind.Unspecified).AddTicks(9625),
                            Status = 1,
                            UserName = "Walker4"
                        },
                        new
                        {
                            Id = 2,
                            ActivationCode = new Guid("0e5398ab-2bf2-4779-a5f7-f91d3b4e6935"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 10, 24, 22, 34, 18, 369, DateTimeKind.Unspecified).AddTicks(3878),
                            Status = 1,
                            UserName = "Kianna_Berge79"
                        },
                        new
                        {
                            Id = 3,
                            ActivationCode = new Guid("c6adc029-75ea-4e78-8e9d-31122a4674a5"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 11, 15, 22, 10, 33, 75, DateTimeKind.Unspecified).AddTicks(2914),
                            Status = 1,
                            UserName = "Bernardo0"
                        },
                        new
                        {
                            Id = 4,
                            ActivationCode = new Guid("50159c20-d6e9-4a9d-afa0-6bc75772c291"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 12, 15, 5, 1, 31, 317, DateTimeKind.Unspecified).AddTicks(7347),
                            Status = 1,
                            UserName = "Neal65"
                        },
                        new
                        {
                            Id = 5,
                            ActivationCode = new Guid("e01160dd-c6c2-4e6b-a438-1d912447719c"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 1, 28, 21, 48, 42, 665, DateTimeKind.Unspecified).AddTicks(4332),
                            Status = 1,
                            UserName = "Christop61"
                        },
                        new
                        {
                            Id = 6,
                            ActivationCode = new Guid("4370b3fb-6adb-47ea-9a73-2db3e0833883"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 7, 6, 3, 59, 30, 16, DateTimeKind.Unspecified).AddTicks(4706),
                            Status = 1,
                            UserName = "Maida.Franecki53"
                        },
                        new
                        {
                            Id = 7,
                            ActivationCode = new Guid("6c499d90-9818-432f-8496-23cda4b8738f"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 11, 16, 14, 3, 17, 755, DateTimeKind.Unspecified).AddTicks(5294),
                            Status = 1,
                            UserName = "Gisselle_Krajcik6"
                        },
                        new
                        {
                            Id = 8,
                            ActivationCode = new Guid("ed51ed80-fdca-44af-bdcd-feac1c179baf"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 8, 27, 0, 16, 11, 641, DateTimeKind.Unspecified).AddTicks(7998),
                            Status = 1,
                            UserName = "Elna_Pagac10"
                        },
                        new
                        {
                            Id = 9,
                            ActivationCode = new Guid("05f395ce-5b0f-42ea-8572-616ff4a8799d"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 12, 17, 3, 46, 46, 152, DateTimeKind.Unspecified).AddTicks(3366),
                            Status = 1,
                            UserName = "Braeden31"
                        },
                        new
                        {
                            Id = 10,
                            ActivationCode = new Guid("b9b073cd-87c2-488c-aafa-ca5028754fca"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 2, 9, 10, 50, 16, 367, DateTimeKind.Unspecified).AddTicks(7838),
                            Status = 1,
                            UserName = "Bonnie_Sporer"
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserLanguage", b =>
                {
                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GivenBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("LanguageID", "AppUserID");

                    b.HasIndex("AppUserID");

                    b.ToTable("AppUsersLanguages");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("AppUserProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 11, 1, 2, 7, 59, 791, DateTimeKind.Unspecified).AddTicks(5104),
                            FirstName = "Megan",
                            LastName = "Haley",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 3, 11, 10, 26, 24, 133, DateTimeKind.Unspecified).AddTicks(5065),
                            FirstName = "Melvin",
                            LastName = "Cassin",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 3, 26, 2, 38, 37, 505, DateTimeKind.Unspecified).AddTicks(9707),
                            FirstName = "Vicki",
                            LastName = "Heathcote",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 4, 6, 11, 34, 36, 0, DateTimeKind.Unspecified).AddTicks(554),
                            FirstName = "Harry",
                            LastName = "Gislason",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 6, 5, 9, 59, 37, 758, DateTimeKind.Unspecified).AddTicks(2713),
                            FirstName = "Joey",
                            LastName = "Schneider",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 9, 27, 18, 42, 12, 445, DateTimeKind.Unspecified).AddTicks(8725),
                            FirstName = "Marion",
                            LastName = "Walter",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2021, 5, 25, 13, 39, 21, 18, DateTimeKind.Unspecified).AddTicks(539),
                            FirstName = "Wendy",
                            LastName = "Carroll",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 6, 14, 8, 49, 38, 530, DateTimeKind.Unspecified).AddTicks(8738),
                            FirstName = "Rodney",
                            LastName = "Boyle",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 7, 4, 19, 2, 24, 199, DateTimeKind.Unspecified).AddTicks(6668),
                            FirstName = "Tony",
                            LastName = "Skiles",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2021, 8, 28, 16, 56, 25, 466, DateTimeKind.Unspecified).AddTicks(6904),
                            FirstName = "Norma",
                            LastName = "Howell",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 5, 20, 8, 44, 51, 124, DateTimeKind.Unspecified).AddTicks(9928),
                            Name = "Outdoors",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 8, 17, 12, 4, 23, 555, DateTimeKind.Unspecified).AddTicks(6348),
                            Name = "Electronics",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 2, 14, 8, 56, 36, 742, DateTimeKind.Unspecified).AddTicks(6302),
                            Name = "Kids",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 4, 17, 6, 23, 47, 739, DateTimeKind.Unspecified).AddTicks(8405),
                            Name = "Outdoors",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 1, 26, 16, 50, 46, 634, DateTimeKind.Unspecified).AddTicks(5265),
                            Name = "Garden",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 9, 16, 18, 24, 10, 575, DateTimeKind.Unspecified).AddTicks(3504),
                            Name = "Clothing",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2021, 10, 17, 17, 16, 40, 377, DateTimeKind.Unspecified).AddTicks(9822),
                            Name = "Tools",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2021, 7, 16, 8, 29, 50, 969, DateTimeKind.Unspecified).AddTicks(6643),
                            Name = "Grocery",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 9, 24, 12, 46, 53, 442, DateTimeKind.Unspecified).AddTicks(7905),
                            Name = "Electronics",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2022, 1, 6, 6, 12, 46, 472, DateTimeKind.Unspecified).AddTicks(1633),
                            Name = "Health",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Urunler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 5, 5, 3, 21, 45, 806, DateTimeKind.Unspecified).AddTicks(2239),
                            Name = "Intelligent Concrete Fish",
                            Price = 54m,
                            Status = 1,
                            Stock = 106
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2021, 5, 2, 7, 19, 37, 48, DateTimeKind.Unspecified).AddTicks(8798),
                            Name = "Awesome Granite Ball",
                            Price = 52m,
                            Status = 1,
                            Stock = 38
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 7, 19, 3, 7, 28, 410, DateTimeKind.Unspecified).AddTicks(5326),
                            Name = "Gorgeous Metal Chair",
                            Price = 54m,
                            Status = 1,
                            Stock = 113
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 6, 13, 13, 31, 36, 757, DateTimeKind.Unspecified).AddTicks(6100),
                            Name = "Gorgeous Concrete Shoes",
                            Price = 52m,
                            Status = 1,
                            Stock = 153
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 4, 21, 19, 3, 12, 46, DateTimeKind.Unspecified).AddTicks(9923),
                            Name = "Small Granite Mouse",
                            Price = 53m,
                            Status = 1,
                            Stock = 123
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2022, 11, 29, 18, 29, 17, 175, DateTimeKind.Unspecified).AddTicks(1282),
                            Name = "Sleek Wooden Bike",
                            Price = 49m,
                            Status = 1,
                            Stock = 145
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 5, 9, 21, 38, 5, 111, DateTimeKind.Unspecified).AddTicks(4372),
                            Name = "Handcrafted Concrete Shoes",
                            Price = 53m,
                            Status = 1,
                            Stock = 127
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2022, 6, 19, 3, 19, 30, 480, DateTimeKind.Unspecified).AddTicks(5341),
                            Name = "Licensed Concrete Ball",
                            Price = 52m,
                            Status = 1,
                            Stock = 82
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2022, 10, 4, 21, 41, 0, 322, DateTimeKind.Unspecified).AddTicks(7568),
                            Name = "Incredible Metal Chicken",
                            Price = 49m,
                            Status = 1,
                            Stock = 115
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 5, 14, 15, 43, 52, 898, DateTimeKind.Unspecified).AddTicks(1521),
                            Name = "Licensed Granite Bike",
                            Price = 49m,
                            Status = 1,
                            Stock = 155
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 11, 12, 15, 35, 0, 733, DateTimeKind.Unspecified).AddTicks(2671),
                            Name = "Rustic Metal Sausages",
                            Price = 54m,
                            Status = 1,
                            Stock = 84
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2021, 5, 6, 18, 49, 37, 837, DateTimeKind.Unspecified).AddTicks(6369),
                            Name = "Fantastic Concrete Chair",
                            Price = 54m,
                            Status = 1,
                            Stock = 148
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 8, 5, 9, 48, 3, 114, DateTimeKind.Unspecified).AddTicks(7960),
                            Name = "Practical Frozen Sausages",
                            Price = 50m,
                            Status = 1,
                            Stock = 22
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 8, 6, 0, 45, 28, 77, DateTimeKind.Unspecified).AddTicks(2129),
                            Name = "Sleek Fresh Chicken",
                            Price = 53m,
                            Status = 1,
                            Stock = 10
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 8, 15, 6, 25, 59, 747, DateTimeKind.Unspecified).AddTicks(8192),
                            Name = "Tasty Soft Chair",
                            Price = 53m,
                            Status = 1,
                            Stock = 152
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 9, 11, 9, 9, 21, 416, DateTimeKind.Unspecified).AddTicks(6571),
                            Name = "Gorgeous Concrete Chips",
                            Price = 57m,
                            Status = 1,
                            Stock = 49
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 5, 6, 12, 5, 19, 410, DateTimeKind.Unspecified).AddTicks(971),
                            Name = "Rustic Fresh Hat",
                            Price = 51m,
                            Status = 1,
                            Stock = 56
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 11, 2, 1, 29, 54, 41, DateTimeKind.Unspecified).AddTicks(8823),
                            Name = "Licensed Metal Mouse",
                            Price = 56m,
                            Status = 1,
                            Stock = 22
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 5, 21, 20, 34, 950, DateTimeKind.Unspecified).AddTicks(3792),
                            Name = "Gorgeous Metal Hat",
                            Price = 54m,
                            Status = 1,
                            Stock = 90
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 5, 13, 10, 37, 39, 911, DateTimeKind.Unspecified).AddTicks(324),
                            Name = "Refined Cotton Sausages",
                            Price = 56m,
                            Status = 1,
                            Stock = 17
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 5, 26, 8, 48, 8, 847, DateTimeKind.Unspecified).AddTicks(1782),
                            Name = "Gorgeous Metal Keyboard",
                            Price = 51m,
                            Status = 1,
                            Stock = 61
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 6, 8, 1, 50, 10, 908, DateTimeKind.Unspecified).AddTicks(1864),
                            Name = "Ergonomic Frozen Fish",
                            Price = 55m,
                            Status = 1,
                            Stock = 21
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 9, 15, 21, 43, 2, 475, DateTimeKind.Unspecified).AddTicks(6177),
                            Name = "Unbranded Rubber Computer",
                            Price = 56m,
                            Status = 1,
                            Stock = 113
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 3, 28, 20, 58, 12, 34, DateTimeKind.Unspecified).AddTicks(4432),
                            Name = "Intelligent Fresh Tuna",
                            Price = 52m,
                            Status = 1,
                            Stock = 197
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 10, 4, 20, 57, 57, 83, DateTimeKind.Unspecified).AddTicks(8295),
                            Name = "Handcrafted Metal Cheese",
                            Price = 56m,
                            Status = 1,
                            Stock = 105
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2022, 12, 2, 13, 23, 54, 68, DateTimeKind.Unspecified).AddTicks(4974),
                            Name = "Tasty Cotton Salad",
                            Price = 55m,
                            Status = 1,
                            Stock = 44
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 10, 25, 18, 56, 29, 883, DateTimeKind.Unspecified).AddTicks(4080),
                            Name = "Sleek Concrete Fish",
                            Price = 57m,
                            Status = 1,
                            Stock = 193
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2022, 3, 27, 10, 39, 42, 508, DateTimeKind.Unspecified).AddTicks(19),
                            Name = "Intelligent Frozen Bacon",
                            Price = 56m,
                            Status = 1,
                            Stock = 126
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 8, 20, 14, 48, 38, 922, DateTimeKind.Unspecified).AddTicks(6044),
                            Name = "Incredible Fresh Gloves",
                            Price = 51m,
                            Status = 1,
                            Stock = 115
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2021, 8, 6, 15, 35, 50, 721, DateTimeKind.Unspecified).AddTicks(2337),
                            Name = "Intelligent Rubber Pizza",
                            Price = 53m,
                            Status = 1,
                            Stock = 44
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UrunOzellikleri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#7c7247",
                            CreatedDate = new DateTime(2021, 11, 10, 20, 42, 15, 29, DateTimeKind.Unspecified).AddTicks(6236),
                            Height = 58,
                            Status = 1,
                            Width = 177
                        },
                        new
                        {
                            Id = 2,
                            Color = "#4a062d",
                            CreatedDate = new DateTime(2021, 7, 10, 9, 41, 39, 258, DateTimeKind.Unspecified).AddTicks(7965),
                            Height = 91,
                            Status = 1,
                            Width = 137
                        },
                        new
                        {
                            Id = 3,
                            Color = "#2f7b38",
                            CreatedDate = new DateTime(2021, 8, 31, 23, 33, 20, 868, DateTimeKind.Unspecified).AddTicks(3708),
                            Height = 140,
                            Status = 1,
                            Width = 39
                        },
                        new
                        {
                            Id = 4,
                            Color = "#020044",
                            CreatedDate = new DateTime(2022, 3, 22, 13, 25, 19, 805, DateTimeKind.Unspecified).AddTicks(907),
                            Height = 127,
                            Status = 1,
                            Width = 143
                        },
                        new
                        {
                            Id = 5,
                            Color = "#5c3e43",
                            CreatedDate = new DateTime(2022, 3, 29, 15, 38, 2, 209, DateTimeKind.Unspecified).AddTicks(344),
                            Height = 167,
                            Status = 1,
                            Width = 31
                        },
                        new
                        {
                            Id = 6,
                            Color = "#004653",
                            CreatedDate = new DateTime(2022, 8, 30, 18, 36, 53, 528, DateTimeKind.Unspecified).AddTicks(3698),
                            Height = 53,
                            Status = 1,
                            Width = 75
                        },
                        new
                        {
                            Id = 7,
                            Color = "#646d5b",
                            CreatedDate = new DateTime(2022, 12, 5, 0, 8, 35, 265, DateTimeKind.Unspecified).AddTicks(7555),
                            Height = 73,
                            Status = 1,
                            Width = 65
                        },
                        new
                        {
                            Id = 8,
                            Color = "#455432",
                            CreatedDate = new DateTime(2022, 2, 2, 3, 25, 38, 658, DateTimeKind.Unspecified).AddTicks(4528),
                            Height = 66,
                            Status = 1,
                            Width = 109
                        },
                        new
                        {
                            Id = 9,
                            Color = "#294003",
                            CreatedDate = new DateTime(2022, 3, 7, 5, 42, 58, 337, DateTimeKind.Unspecified).AddTicks(824),
                            Height = 179,
                            Status = 1,
                            Width = 30
                        },
                        new
                        {
                            Id = 10,
                            Color = "#163f42",
                            CreatedDate = new DateTime(2022, 8, 14, 10, 28, 27, 34, DateTimeKind.Unspecified).AddTicks(54),
                            Height = 186,
                            Status = 1,
                            Width = 46
                        },
                        new
                        {
                            Id = 11,
                            Color = "#274263",
                            CreatedDate = new DateTime(2022, 3, 14, 21, 7, 47, 969, DateTimeKind.Unspecified).AddTicks(7609),
                            Height = 61,
                            Status = 1,
                            Width = 99
                        },
                        new
                        {
                            Id = 12,
                            Color = "#69015a",
                            CreatedDate = new DateTime(2022, 1, 3, 17, 27, 5, 761, DateTimeKind.Unspecified).AddTicks(7830),
                            Height = 54,
                            Status = 1,
                            Width = 19
                        },
                        new
                        {
                            Id = 13,
                            Color = "#63451b",
                            CreatedDate = new DateTime(2022, 5, 23, 8, 17, 16, 738, DateTimeKind.Unspecified).AddTicks(768),
                            Height = 54,
                            Status = 1,
                            Width = 145
                        },
                        new
                        {
                            Id = 14,
                            Color = "#121816",
                            CreatedDate = new DateTime(2022, 11, 27, 17, 34, 22, 204, DateTimeKind.Unspecified).AddTicks(2647),
                            Height = 167,
                            Status = 1,
                            Width = 93
                        },
                        new
                        {
                            Id = 15,
                            Color = "#5d1628",
                            CreatedDate = new DateTime(2022, 11, 2, 12, 3, 47, 368, DateTimeKind.Unspecified).AddTicks(9305),
                            Height = 28,
                            Status = 1,
                            Width = 147
                        },
                        new
                        {
                            Id = 16,
                            Color = "#16093c",
                            CreatedDate = new DateTime(2021, 5, 28, 8, 1, 55, 119, DateTimeKind.Unspecified).AddTicks(6932),
                            Height = 125,
                            Status = 1,
                            Width = 98
                        },
                        new
                        {
                            Id = 17,
                            Color = "#5d6753",
                            CreatedDate = new DateTime(2022, 9, 9, 20, 10, 24, 44, DateTimeKind.Unspecified).AddTicks(5031),
                            Height = 94,
                            Status = 1,
                            Width = 116
                        },
                        new
                        {
                            Id = 18,
                            Color = "#2c0d20",
                            CreatedDate = new DateTime(2021, 3, 18, 21, 44, 43, 135, DateTimeKind.Unspecified).AddTicks(1668),
                            Height = 14,
                            Status = 1,
                            Width = 41
                        },
                        new
                        {
                            Id = 19,
                            Color = "#4c380c",
                            CreatedDate = new DateTime(2021, 7, 18, 10, 44, 41, 373, DateTimeKind.Unspecified).AddTicks(9832),
                            Height = 23,
                            Status = 1,
                            Width = 189
                        },
                        new
                        {
                            Id = 20,
                            Color = "#0a1e61",
                            CreatedDate = new DateTime(2022, 4, 18, 21, 20, 31, 381, DateTimeKind.Unspecified).AddTicks(1788),
                            Height = 56,
                            Status = 1,
                            Width = 22
                        },
                        new
                        {
                            Id = 21,
                            Color = "#7c3154",
                            CreatedDate = new DateTime(2022, 7, 30, 1, 42, 30, 291, DateTimeKind.Unspecified).AddTicks(1897),
                            Height = 35,
                            Status = 1,
                            Width = 4
                        },
                        new
                        {
                            Id = 22,
                            Color = "#315a1a",
                            CreatedDate = new DateTime(2022, 10, 15, 23, 44, 7, 217, DateTimeKind.Unspecified).AddTicks(4997),
                            Height = 165,
                            Status = 1,
                            Width = 6
                        },
                        new
                        {
                            Id = 23,
                            Color = "#133d66",
                            CreatedDate = new DateTime(2021, 9, 4, 2, 53, 24, 677, DateTimeKind.Unspecified).AddTicks(7373),
                            Height = 120,
                            Status = 1,
                            Width = 32
                        },
                        new
                        {
                            Id = 24,
                            Color = "#01455b",
                            CreatedDate = new DateTime(2021, 7, 6, 19, 28, 13, 194, DateTimeKind.Unspecified).AddTicks(6914),
                            Height = 172,
                            Status = 1,
                            Width = 39
                        },
                        new
                        {
                            Id = 25,
                            Color = "#170f5d",
                            CreatedDate = new DateTime(2022, 7, 24, 9, 31, 53, 278, DateTimeKind.Unspecified).AddTicks(847),
                            Height = 160,
                            Status = 1,
                            Width = 145
                        },
                        new
                        {
                            Id = 26,
                            Color = "#05486e",
                            CreatedDate = new DateTime(2021, 9, 23, 16, 45, 46, 438, DateTimeKind.Unspecified).AddTicks(572),
                            Height = 74,
                            Status = 1,
                            Width = 36
                        },
                        new
                        {
                            Id = 27,
                            Color = "#4f3b2e",
                            CreatedDate = new DateTime(2021, 6, 11, 4, 50, 7, 904, DateTimeKind.Unspecified).AddTicks(4049),
                            Height = 85,
                            Status = 1,
                            Width = 43
                        },
                        new
                        {
                            Id = 28,
                            Color = "#6d7b47",
                            CreatedDate = new DateTime(2021, 12, 14, 4, 55, 1, 850, DateTimeKind.Unspecified).AddTicks(3639),
                            Height = 116,
                            Status = 1,
                            Width = 186
                        },
                        new
                        {
                            Id = 29,
                            Color = "#570f56",
                            CreatedDate = new DateTime(2022, 9, 23, 9, 30, 12, 137, DateTimeKind.Unspecified).AddTicks(4962),
                            Height = 116,
                            Status = 1,
                            Width = 105
                        },
                        new
                        {
                            Id = 30,
                            Color = "#7a2a4f",
                            CreatedDate = new DateTime(2022, 2, 16, 18, 10, 31, 741, DateTimeKind.Unspecified).AddTicks(9995),
                            Height = 138,
                            Status = 1,
                            Width = 77
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserLanguage", b =>
                {
                    b.HasOne("NLayer.Core.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLayer.Core.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserProfile", b =>
                {
                    b.HasOne("NLayer.Core.Models.AppUser", "AppUser")
                        .WithOne("AppUserProfile")
                        .HasForeignKey("NLayer.Core.Models.AppUserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.HasOne("NLayer.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.HasOne("NLayer.Core.Models.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("NLayer.Core.Models.ProductFeature", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUser", b =>
                {
                    b.Navigation("AppUserProfile");
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Navigation("ProductFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
