// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayer.Repository;

#nullable disable

namespace NLayer.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221206010014_myMigRole")]
    partial class myMigRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NLayer.Core.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserLanguage", b =>
                {
                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GivenBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("LanguageID", "AppUserID");

                    b.HasIndex("AppUserID");

                    b.ToTable("AppUsersLanguages");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("AppUserProfile");
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 4, 5, 10, 26, 25, 191, DateTimeKind.Unspecified).AddTicks(9492),
                            Name = "Movies",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 6, 22, 23, 46, 57, 58, DateTimeKind.Unspecified).AddTicks(1241),
                            Name = "Tools",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 8, 5, 6, 22, 24, 260, DateTimeKind.Unspecified).AddTicks(5649),
                            Name = "Health",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 7, 2, 14, 16, 30, 821, DateTimeKind.Unspecified).AddTicks(2681),
                            Name = "Baby",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 3, 8, 18, 30, 32, 584, DateTimeKind.Unspecified).AddTicks(5826),
                            Name = "Jewelery",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 1, 26, 7, 27, 6, 26, DateTimeKind.Unspecified).AddTicks(4823),
                            Name = "Jewelery",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2021, 12, 5, 0, 25, 43, 124, DateTimeKind.Unspecified).AddTicks(9447),
                            Name = "Kids",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 9, 26, 18, 55, 43, 584, DateTimeKind.Unspecified).AddTicks(1615),
                            Name = "Shoes",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2021, 5, 29, 18, 52, 4, 311, DateTimeKind.Unspecified).AddTicks(232),
                            Name = "Computers",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2021, 8, 14, 21, 30, 0, 643, DateTimeKind.Unspecified).AddTicks(9860),
                            Name = "Electronics",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 12, 6, 4, 0, 13, 662, DateTimeKind.Local).AddTicks(580),
                            LanguageName = "Türkçe",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 12, 6, 4, 0, 13, 663, DateTimeKind.Local).AddTicks(2634),
                            LanguageName = "İngilizce",
                            Level = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 12, 6, 4, 0, 13, 663, DateTimeKind.Local).AddTicks(2642),
                            LanguageName = "Almanca",
                            Level = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Urunler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 1, 7, 9, 34, 5, 32, DateTimeKind.Unspecified).AddTicks(6345),
                            Name = "Rustic Wooden Gloves",
                            Price = 50m,
                            Status = 1,
                            Stock = 159
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 11, 6, 5, 4, 53, 690, DateTimeKind.Unspecified).AddTicks(2976),
                            Name = "Practical Rubber Pizza",
                            Price = 56m,
                            Status = 1,
                            Stock = 110
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 11, 9, 14, 3, 26, 436, DateTimeKind.Unspecified).AddTicks(7421),
                            Name = "Unbranded Cotton Salad",
                            Price = 51m,
                            Status = 1,
                            Stock = 52
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2021, 10, 15, 20, 58, 15, 648, DateTimeKind.Unspecified).AddTicks(7021),
                            Name = "Generic Rubber Table",
                            Price = 53m,
                            Status = 1,
                            Stock = 163
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 7, 10, 10, 16, 1, 615, DateTimeKind.Unspecified).AddTicks(5152),
                            Name = "Handmade Steel Hat",
                            Price = 49m,
                            Status = 1,
                            Stock = 15
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 8, 29, 1, 53, 25, 198, DateTimeKind.Unspecified).AddTicks(4888),
                            Name = "Generic Concrete Mouse",
                            Price = 52m,
                            Status = 1,
                            Stock = 29
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2022, 4, 4, 17, 23, 2, 604, DateTimeKind.Unspecified).AddTicks(1914),
                            Name = "Unbranded Cotton Keyboard",
                            Price = 49m,
                            Status = 1,
                            Stock = 168
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 4, 20, 8, 1, 31, 949, DateTimeKind.Unspecified).AddTicks(8644),
                            Name = "Rustic Frozen Mouse",
                            Price = 51m,
                            Status = 1,
                            Stock = 79
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 7, 25, 5, 13, 3, 965, DateTimeKind.Unspecified).AddTicks(8818),
                            Name = "Generic Concrete Tuna",
                            Price = 49m,
                            Status = 1,
                            Stock = 129
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 12, 23, 16, 19, 25, 17, DateTimeKind.Unspecified).AddTicks(8567),
                            Name = "Unbranded Cotton Gloves",
                            Price = 52m,
                            Status = 1,
                            Stock = 89
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 11, 25, 6, 13, 29, 508, DateTimeKind.Unspecified).AddTicks(1649),
                            Name = "Fantastic Fresh Computer",
                            Price = 53m,
                            Status = 1,
                            Stock = 107
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 7, 21, 4, 36, 26, 79, DateTimeKind.Unspecified).AddTicks(8521),
                            Name = "Handmade Granite Hat",
                            Price = 52m,
                            Status = 1,
                            Stock = 181
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 9, 13, 7, 55, 11, 784, DateTimeKind.Unspecified).AddTicks(6515),
                            Name = "Generic Fresh Chicken",
                            Price = 50m,
                            Status = 1,
                            Stock = 89
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 7, 23, 21, 38, 10, 33, DateTimeKind.Unspecified).AddTicks(5609),
                            Name = "Refined Granite Bacon",
                            Price = 51m,
                            Status = 1,
                            Stock = 49
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2021, 6, 15, 23, 26, 11, 379, DateTimeKind.Unspecified).AddTicks(8189),
                            Name = "Practical Granite Salad",
                            Price = 54m,
                            Status = 1,
                            Stock = 143
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 3, 23, 7, 37, 44, 485, DateTimeKind.Unspecified).AddTicks(2680),
                            Name = "Handcrafted Frozen Bacon",
                            Price = 52m,
                            Status = 1,
                            Stock = 126
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 10, 19, 5, 29, 48, 222, DateTimeKind.Unspecified).AddTicks(2951),
                            Name = "Awesome Wooden Cheese",
                            Price = 51m,
                            Status = 1,
                            Stock = 31
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2021, 6, 20, 2, 24, 12, 678, DateTimeKind.Unspecified).AddTicks(6093),
                            Name = "Sleek Granite Fish",
                            Price = 55m,
                            Status = 1,
                            Stock = 27
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 5, 8, 3, 15, 55, 959, DateTimeKind.Unspecified).AddTicks(955),
                            Name = "Incredible Soft Fish",
                            Price = 51m,
                            Status = 1,
                            Stock = 130
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 7, 3, 5, 12, 38, 646, DateTimeKind.Unspecified).AddTicks(7262),
                            Name = "Awesome Wooden Soap",
                            Price = 49m,
                            Status = 1,
                            Stock = 53
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2021, 6, 12, 16, 34, 54, 813, DateTimeKind.Unspecified).AddTicks(3742),
                            Name = "Handmade Steel Computer",
                            Price = 49m,
                            Status = 1,
                            Stock = 144
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 11, 12, 22, 27, 50, 737, DateTimeKind.Unspecified).AddTicks(632),
                            Name = "Gorgeous Rubber Shoes",
                            Price = 51m,
                            Status = 1,
                            Stock = 149
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 10, 14, 23, 51, 12, 318, DateTimeKind.Unspecified).AddTicks(1970),
                            Name = "Awesome Steel Computer",
                            Price = 53m,
                            Status = 1,
                            Stock = 70
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 1, 17, 18, 44, 58, 935, DateTimeKind.Unspecified).AddTicks(8082),
                            Name = "Rustic Cotton Chicken",
                            Price = 50m,
                            Status = 1,
                            Stock = 18
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2022, 4, 7, 3, 48, 32, 954, DateTimeKind.Unspecified).AddTicks(6865),
                            Name = "Generic Metal Shirt",
                            Price = 52m,
                            Status = 1,
                            Stock = 51
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 9, 9, 17, 4, 37, 413, DateTimeKind.Unspecified).AddTicks(2147),
                            Name = "Fantastic Granite Chips",
                            Price = 57m,
                            Status = 1,
                            Stock = 173
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 2, 12, 3, 4, 19, 768, DateTimeKind.Unspecified).AddTicks(3778),
                            Name = "Small Concrete Pizza",
                            Price = 55m,
                            Status = 1,
                            Stock = 182
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 3, 20, 1, 18, 2, 100, DateTimeKind.Unspecified).AddTicks(3397),
                            Name = "Intelligent Rubber Mouse",
                            Price = 54m,
                            Status = 1,
                            Stock = 172
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2022, 5, 6, 1, 13, 18, 236, DateTimeKind.Unspecified).AddTicks(3121),
                            Name = "Refined Frozen Pants",
                            Price = 49m,
                            Status = 1,
                            Stock = 9
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 7, 6, 23, 46, 21, 588, DateTimeKind.Unspecified).AddTicks(8050),
                            Name = "Licensed Fresh Shoes",
                            Price = 51m,
                            Status = 1,
                            Stock = 33
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UrunOzellikleri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#2c4461",
                            CreatedDate = new DateTime(2021, 11, 18, 4, 5, 29, 918, DateTimeKind.Unspecified).AddTicks(7856),
                            Height = 186,
                            Status = 1,
                            Width = 101
                        },
                        new
                        {
                            Id = 2,
                            Color = "#2a0956",
                            CreatedDate = new DateTime(2022, 2, 23, 16, 32, 21, 403, DateTimeKind.Unspecified).AddTicks(7800),
                            Height = 76,
                            Status = 1,
                            Width = 142
                        },
                        new
                        {
                            Id = 3,
                            Color = "#49175b",
                            CreatedDate = new DateTime(2021, 11, 22, 20, 47, 47, 383, DateTimeKind.Unspecified).AddTicks(483),
                            Height = 168,
                            Status = 1,
                            Width = 84
                        },
                        new
                        {
                            Id = 4,
                            Color = "#2f0051",
                            CreatedDate = new DateTime(2022, 3, 30, 13, 1, 41, 254, DateTimeKind.Unspecified).AddTicks(4241),
                            Height = 143,
                            Status = 1,
                            Width = 12
                        },
                        new
                        {
                            Id = 5,
                            Color = "#286e79",
                            CreatedDate = new DateTime(2021, 7, 8, 19, 22, 27, 977, DateTimeKind.Unspecified).AddTicks(1528),
                            Height = 161,
                            Status = 1,
                            Width = 94
                        },
                        new
                        {
                            Id = 6,
                            Color = "#7f301b",
                            CreatedDate = new DateTime(2022, 2, 21, 16, 6, 22, 826, DateTimeKind.Unspecified).AddTicks(6990),
                            Height = 93,
                            Status = 1,
                            Width = 109
                        },
                        new
                        {
                            Id = 7,
                            Color = "#321450",
                            CreatedDate = new DateTime(2021, 8, 21, 16, 21, 38, 162, DateTimeKind.Unspecified).AddTicks(4297),
                            Height = 97,
                            Status = 1,
                            Width = 101
                        },
                        new
                        {
                            Id = 8,
                            Color = "#1c5c0a",
                            CreatedDate = new DateTime(2021, 8, 10, 19, 43, 50, 194, DateTimeKind.Unspecified).AddTicks(4725),
                            Height = 100,
                            Status = 1,
                            Width = 76
                        },
                        new
                        {
                            Id = 9,
                            Color = "#791658",
                            CreatedDate = new DateTime(2022, 4, 4, 8, 32, 22, 677, DateTimeKind.Unspecified).AddTicks(7557),
                            Height = 112,
                            Status = 1,
                            Width = 27
                        },
                        new
                        {
                            Id = 10,
                            Color = "#054345",
                            CreatedDate = new DateTime(2021, 9, 13, 11, 41, 24, 719, DateTimeKind.Unspecified).AddTicks(5933),
                            Height = 59,
                            Status = 1,
                            Width = 80
                        },
                        new
                        {
                            Id = 11,
                            Color = "#511450",
                            CreatedDate = new DateTime(2022, 6, 6, 19, 49, 34, 92, DateTimeKind.Unspecified).AddTicks(8293),
                            Height = 37,
                            Status = 1,
                            Width = 104
                        },
                        new
                        {
                            Id = 12,
                            Color = "#1c140a",
                            CreatedDate = new DateTime(2022, 3, 11, 10, 34, 44, 788, DateTimeKind.Unspecified).AddTicks(2649),
                            Height = 164,
                            Status = 1,
                            Width = 183
                        },
                        new
                        {
                            Id = 13,
                            Color = "#4f5e54",
                            CreatedDate = new DateTime(2022, 7, 13, 3, 1, 12, 7, DateTimeKind.Unspecified).AddTicks(9456),
                            Height = 101,
                            Status = 1,
                            Width = 77
                        },
                        new
                        {
                            Id = 14,
                            Color = "#133776",
                            CreatedDate = new DateTime(2022, 1, 8, 10, 38, 3, 331, DateTimeKind.Unspecified).AddTicks(8886),
                            Height = 147,
                            Status = 1,
                            Width = 36
                        },
                        new
                        {
                            Id = 15,
                            Color = "#7c7a2e",
                            CreatedDate = new DateTime(2021, 6, 1, 14, 9, 13, 514, DateTimeKind.Unspecified).AddTicks(8575),
                            Height = 113,
                            Status = 1,
                            Width = 75
                        },
                        new
                        {
                            Id = 16,
                            Color = "#235e42",
                            CreatedDate = new DateTime(2022, 7, 26, 8, 39, 18, 257, DateTimeKind.Unspecified).AddTicks(418),
                            Height = 11,
                            Status = 1,
                            Width = 135
                        },
                        new
                        {
                            Id = 17,
                            Color = "#360a1f",
                            CreatedDate = new DateTime(2021, 6, 24, 16, 34, 30, 863, DateTimeKind.Unspecified).AddTicks(1080),
                            Height = 150,
                            Status = 1,
                            Width = 64
                        },
                        new
                        {
                            Id = 18,
                            Color = "#487b7b",
                            CreatedDate = new DateTime(2022, 3, 11, 15, 51, 14, 306, DateTimeKind.Unspecified).AddTicks(2922),
                            Height = 121,
                            Status = 1,
                            Width = 28
                        },
                        new
                        {
                            Id = 19,
                            Color = "#390e1f",
                            CreatedDate = new DateTime(2022, 1, 22, 8, 13, 44, 7, DateTimeKind.Unspecified).AddTicks(1083),
                            Height = 32,
                            Status = 1,
                            Width = 93
                        },
                        new
                        {
                            Id = 20,
                            Color = "#56003c",
                            CreatedDate = new DateTime(2022, 9, 18, 23, 53, 50, 492, DateTimeKind.Unspecified).AddTicks(3039),
                            Height = 138,
                            Status = 1,
                            Width = 42
                        },
                        new
                        {
                            Id = 21,
                            Color = "#7c7034",
                            CreatedDate = new DateTime(2022, 11, 2, 4, 1, 15, 459, DateTimeKind.Unspecified).AddTicks(5397),
                            Height = 25,
                            Status = 1,
                            Width = 111
                        },
                        new
                        {
                            Id = 22,
                            Color = "#5e5312",
                            CreatedDate = new DateTime(2022, 11, 28, 3, 12, 56, 725, DateTimeKind.Unspecified).AddTicks(4827),
                            Height = 199,
                            Status = 1,
                            Width = 128
                        },
                        new
                        {
                            Id = 23,
                            Color = "#4b1c3b",
                            CreatedDate = new DateTime(2022, 3, 17, 8, 56, 51, 430, DateTimeKind.Unspecified).AddTicks(1583),
                            Height = 119,
                            Status = 1,
                            Width = 93
                        },
                        new
                        {
                            Id = 24,
                            Color = "#735b13",
                            CreatedDate = new DateTime(2021, 3, 18, 18, 25, 18, 364, DateTimeKind.Unspecified).AddTicks(7328),
                            Height = 191,
                            Status = 1,
                            Width = 13
                        },
                        new
                        {
                            Id = 25,
                            Color = "#11512b",
                            CreatedDate = new DateTime(2021, 6, 21, 4, 27, 31, 580, DateTimeKind.Unspecified).AddTicks(7745),
                            Height = 177,
                            Status = 1,
                            Width = 169
                        },
                        new
                        {
                            Id = 26,
                            Color = "#274702",
                            CreatedDate = new DateTime(2022, 7, 5, 13, 16, 27, 931, DateTimeKind.Unspecified).AddTicks(3733),
                            Height = 21,
                            Status = 1,
                            Width = 92
                        },
                        new
                        {
                            Id = 27,
                            Color = "#7d513b",
                            CreatedDate = new DateTime(2022, 5, 14, 20, 43, 40, 38, DateTimeKind.Unspecified).AddTicks(6633),
                            Height = 5,
                            Status = 1,
                            Width = 66
                        },
                        new
                        {
                            Id = 28,
                            Color = "#16374f",
                            CreatedDate = new DateTime(2021, 12, 3, 13, 59, 2, 468, DateTimeKind.Unspecified).AddTicks(3474),
                            Height = 148,
                            Status = 1,
                            Width = 195
                        },
                        new
                        {
                            Id = 29,
                            Color = "#641732",
                            CreatedDate = new DateTime(2021, 9, 11, 6, 20, 46, 980, DateTimeKind.Unspecified).AddTicks(7463),
                            Height = 200,
                            Status = 1,
                            Width = 166
                        },
                        new
                        {
                            Id = 30,
                            Color = "#5e1f04",
                            CreatedDate = new DateTime(2021, 9, 6, 6, 30, 26, 474, DateTimeKind.Unspecified).AddTicks(9360),
                            Height = 196,
                            Status = 1,
                            Width = 13
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserLanguage", b =>
                {
                    b.HasOne("NLayer.Core.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLayer.Core.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserProfile", b =>
                {
                    b.HasOne("NLayer.Core.Models.AppUser", "AppUser")
                        .WithOne("AppUserProfile")
                        .HasForeignKey("NLayer.Core.Models.AppUserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.HasOne("NLayer.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.HasOne("NLayer.Core.Models.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("NLayer.Core.Models.ProductFeature", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUser", b =>
                {
                    b.Navigation("AppUserProfile");
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Navigation("ProductFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
