// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayer.Repository;

#nullable disable

namespace NLayer.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221207212048_NewMig")]
    partial class NewMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NLayer.Core.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivationCode = new Guid("95e9dd87-4d83-42c8-8a66-41eb4690d9ac"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 8, 19, 22, 19, 31, 427, DateTimeKind.Unspecified).AddTicks(9622),
                            Status = 1,
                            UserName = "Citlalli_Sipes69"
                        },
                        new
                        {
                            Id = 2,
                            ActivationCode = new Guid("0c622f46-a541-44e0-9663-c19c20092339"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 6, 13, 16, 47, 19, 49, DateTimeKind.Unspecified).AddTicks(8647),
                            Status = 1,
                            UserName = "Elizabeth7"
                        },
                        new
                        {
                            Id = 3,
                            ActivationCode = new Guid("e4571044-f763-41f1-951b-ecbc2484f452"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 7, 21, 0, 56, 40, 853, DateTimeKind.Unspecified).AddTicks(4193),
                            Status = 1,
                            UserName = "Lillie.Steuber92"
                        },
                        new
                        {
                            Id = 4,
                            ActivationCode = new Guid("3f1a443d-39e4-4d7e-b902-db3a2ab267e9"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 3, 11, 9, 15, 45, 755, DateTimeKind.Unspecified).AddTicks(9426),
                            Status = 1,
                            UserName = "Myrna58"
                        },
                        new
                        {
                            Id = 5,
                            ActivationCode = new Guid("7aedc4a4-de97-4792-b0fb-84b0bc9ee118"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 6, 19, 13, 53, 33, 162, DateTimeKind.Unspecified).AddTicks(1499),
                            Status = 1,
                            UserName = "Cruz39"
                        },
                        new
                        {
                            Id = 6,
                            ActivationCode = new Guid("db1c5369-f674-4316-973b-6cdba1d8f021"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 7, 10, 0, 54, 32, 781, DateTimeKind.Unspecified).AddTicks(4299),
                            Status = 1,
                            UserName = "Osborne5"
                        },
                        new
                        {
                            Id = 7,
                            ActivationCode = new Guid("be2a659a-456f-42c2-bf41-98afe920ade3"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 10, 29, 11, 49, 31, 999, DateTimeKind.Unspecified).AddTicks(8573),
                            Status = 1,
                            UserName = "Johnny0"
                        },
                        new
                        {
                            Id = 8,
                            ActivationCode = new Guid("5dbc9080-768a-48d0-a058-0a093fbf1871"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 10, 12, 8, 8, 17, 100, DateTimeKind.Unspecified).AddTicks(3624),
                            Status = 1,
                            UserName = "Emma.Larson66"
                        },
                        new
                        {
                            Id = 9,
                            ActivationCode = new Guid("02fe0787-ff84-4048-95e7-0a14e61b8fd9"),
                            Active = false,
                            CreatedDate = new DateTime(2021, 3, 28, 9, 2, 14, 448, DateTimeKind.Unspecified).AddTicks(2219),
                            Status = 1,
                            UserName = "Maximillian.Hilpert"
                        },
                        new
                        {
                            Id = 10,
                            ActivationCode = new Guid("aa35cfa2-5d15-4733-a60f-12e29754375c"),
                            Active = false,
                            CreatedDate = new DateTime(2022, 4, 5, 10, 43, 19, 306, DateTimeKind.Unspecified).AddTicks(4615),
                            Status = 1,
                            UserName = "Adela_Wisoky"
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserLanguage", b =>
                {
                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GivenBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("LanguageID", "AppUserID");

                    b.HasIndex("AppUserID");

                    b.ToTable("AppUsersLanguages");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("AppUserProfile");
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 1, 3, 18, 5, 10, 960, DateTimeKind.Unspecified).AddTicks(143),
                            Name = "Clothing",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 4, 6, 23, 56, 14, 69, DateTimeKind.Unspecified).AddTicks(4226),
                            Name = "Shoes",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 9, 21, 17, 26, 34, 546, DateTimeKind.Unspecified).AddTicks(5661),
                            Name = "Movies",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 5, 12, 8, 41, 11, 910, DateTimeKind.Unspecified).AddTicks(4876),
                            Name = "Automotive",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 10, 8, 7, 25, 31, 822, DateTimeKind.Unspecified).AddTicks(171),
                            Name = "Jewelery",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 10, 16, 5, 53, 12, 898, DateTimeKind.Unspecified).AddTicks(7271),
                            Name = "Jewelery",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2021, 7, 13, 2, 27, 35, 107, DateTimeKind.Unspecified).AddTicks(1678),
                            Name = "Sports",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 8, 16, 4, 20, 12, 475, DateTimeKind.Unspecified).AddTicks(6354),
                            Name = "Automotive",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 8, 24, 10, 24, 2, 465, DateTimeKind.Unspecified).AddTicks(9722),
                            Name = "Electronics",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2022, 6, 8, 10, 58, 48, 979, DateTimeKind.Unspecified).AddTicks(7836),
                            Name = "Electronics",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Urunler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 10, 6, 21, 43, 1, 957, DateTimeKind.Unspecified).AddTicks(8102),
                            Name = "Sleek Frozen Chicken",
                            Price = 52m,
                            Status = 1,
                            Stock = 30
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 10, 18, 3, 8, 23, 776, DateTimeKind.Unspecified).AddTicks(9138),
                            Name = "Refined Frozen Chair",
                            Price = 56m,
                            Status = 1,
                            Stock = 106
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 8, 24, 2, 26, 25, 244, DateTimeKind.Unspecified).AddTicks(1206),
                            Name = "Small Steel Fish",
                            Price = 56m,
                            Status = 1,
                            Stock = 182
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 8, 14, 5, 1, 3, 858, DateTimeKind.Unspecified).AddTicks(3377),
                            Name = "Intelligent Wooden Computer",
                            Price = 56m,
                            Status = 1,
                            Stock = 119
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 7, 19, 4, 26, 25, 880, DateTimeKind.Unspecified).AddTicks(7013),
                            Name = "Fantastic Plastic Bike",
                            Price = 56m,
                            Status = 1,
                            Stock = 103
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 1, 4, 23, 46, 45, 713, DateTimeKind.Unspecified).AddTicks(5108),
                            Name = "Rustic Soft Towels",
                            Price = 51m,
                            Status = 1,
                            Stock = 163
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 3, 27, 12, 32, 21, 359, DateTimeKind.Unspecified).AddTicks(3357),
                            Name = "Handcrafted Plastic Fish",
                            Price = 57m,
                            Status = 1,
                            Stock = 50
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 5, 28, 21, 37, 2, 993, DateTimeKind.Unspecified).AddTicks(7156),
                            Name = "Generic Frozen Shoes",
                            Price = 52m,
                            Status = 1,
                            Stock = 167
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 8, 5, 4, 47, 10, 843, DateTimeKind.Unspecified).AddTicks(5556),
                            Name = "Tasty Metal Towels",
                            Price = 53m,
                            Status = 1,
                            Stock = 57
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 7, 5, 21, 26, 2, 966, DateTimeKind.Unspecified).AddTicks(4865),
                            Name = "Unbranded Soft Towels",
                            Price = 56m,
                            Status = 1,
                            Stock = 42
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 8, 27, 4, 46, 3, 910, DateTimeKind.Unspecified).AddTicks(5241),
                            Name = "Rustic Soft Shoes",
                            Price = 56m,
                            Status = 1,
                            Stock = 192
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2022, 11, 20, 8, 34, 8, 380, DateTimeKind.Unspecified).AddTicks(596),
                            Name = "Licensed Fresh Car",
                            Price = 51m,
                            Status = 1,
                            Stock = 106
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 11, 16, 20, 25, 1, 195, DateTimeKind.Unspecified).AddTicks(1662),
                            Name = "Refined Soft Hat",
                            Price = 53m,
                            Status = 1,
                            Stock = 176
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 4, 4, 21, 1, 29, 18, DateTimeKind.Unspecified).AddTicks(5188),
                            Name = "Licensed Soft Tuna",
                            Price = 56m,
                            Status = 1,
                            Stock = 133
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2022, 5, 20, 17, 47, 15, 750, DateTimeKind.Unspecified).AddTicks(7804),
                            Name = "Small Wooden Gloves",
                            Price = 56m,
                            Status = 1,
                            Stock = 160
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 1, 9, 15, 50, 24, 893, DateTimeKind.Unspecified).AddTicks(2928),
                            Name = "Practical Steel Ball",
                            Price = 57m,
                            Status = 1,
                            Stock = 19
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 6, 24, 22, 34, 48, 864, DateTimeKind.Unspecified).AddTicks(9182),
                            Name = "Fantastic Concrete Chicken",
                            Price = 56m,
                            Status = 1,
                            Stock = 175
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 6, 5, 23, 9, 8, 736, DateTimeKind.Unspecified).AddTicks(710),
                            Name = "Handmade Rubber Hat",
                            Price = 55m,
                            Status = 1,
                            Stock = 2
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 4, 12, 21, 55, 6, 563, DateTimeKind.Unspecified).AddTicks(3515),
                            Name = "Gorgeous Metal Pants",
                            Price = 56m,
                            Status = 1,
                            Stock = 52
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 5, 15, 6, 56, 2, 51, DateTimeKind.Unspecified).AddTicks(9565),
                            Name = "Rustic Metal Table",
                            Price = 55m,
                            Status = 1,
                            Stock = 135
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 6, 14, 4, 13, 50, 332, DateTimeKind.Unspecified).AddTicks(795),
                            Name = "Fantastic Steel Pants",
                            Price = 56m,
                            Status = 1,
                            Stock = 150
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 1, 21, 5, 22, 18, 909, DateTimeKind.Unspecified).AddTicks(3364),
                            Name = "Generic Rubber Table",
                            Price = 50m,
                            Status = 1,
                            Stock = 2
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 5, 14, 23, 36, 46, 512, DateTimeKind.Unspecified).AddTicks(9515),
                            Name = "Incredible Wooden Shirt",
                            Price = 56m,
                            Status = 1,
                            Stock = 36
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2022, 9, 20, 21, 46, 27, 329, DateTimeKind.Unspecified).AddTicks(6629),
                            Name = "Generic Cotton Shoes",
                            Price = 56m,
                            Status = 1,
                            Stock = 105
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2022, 2, 27, 3, 41, 36, 515, DateTimeKind.Unspecified).AddTicks(7861),
                            Name = "Generic Frozen Mouse",
                            Price = 53m,
                            Status = 1,
                            Stock = 178
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2022, 10, 13, 18, 51, 59, 753, DateTimeKind.Unspecified).AddTicks(7729),
                            Name = "Sleek Fresh Bacon",
                            Price = 49m,
                            Status = 1,
                            Stock = 45
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 11, 3, 19, 12, 23, 397, DateTimeKind.Unspecified).AddTicks(4826),
                            Name = "Generic Fresh Chair",
                            Price = 55m,
                            Status = 1,
                            Stock = 138
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 5, 17, 15, 1, 25, 603, DateTimeKind.Unspecified).AddTicks(222),
                            Name = "Practical Granite Chicken",
                            Price = 53m,
                            Status = 1,
                            Stock = 4
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2022, 4, 4, 1, 14, 52, 779, DateTimeKind.Unspecified).AddTicks(4472),
                            Name = "Licensed Metal Pizza",
                            Price = 50m,
                            Status = 1,
                            Stock = 8
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2021, 10, 13, 12, 40, 49, 768, DateTimeKind.Unspecified).AddTicks(9075),
                            Name = "Tasty Metal Car",
                            Price = 57m,
                            Status = 1,
                            Stock = 99
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UrunOzellikleri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#2e662f",
                            CreatedDate = new DateTime(2021, 5, 3, 17, 9, 28, 529, DateTimeKind.Unspecified).AddTicks(7940),
                            Height = 195,
                            Status = 1,
                            Width = 162
                        },
                        new
                        {
                            Id = 2,
                            Color = "#213221",
                            CreatedDate = new DateTime(2021, 8, 24, 8, 42, 7, 962, DateTimeKind.Unspecified).AddTicks(9615),
                            Height = 64,
                            Status = 1,
                            Width = 62
                        },
                        new
                        {
                            Id = 3,
                            Color = "#043d27",
                            CreatedDate = new DateTime(2022, 2, 22, 23, 6, 26, 802, DateTimeKind.Unspecified).AddTicks(6006),
                            Height = 193,
                            Status = 1,
                            Width = 61
                        },
                        new
                        {
                            Id = 4,
                            Color = "#430306",
                            CreatedDate = new DateTime(2021, 4, 1, 0, 26, 25, 837, DateTimeKind.Unspecified).AddTicks(984),
                            Height = 44,
                            Status = 1,
                            Width = 163
                        },
                        new
                        {
                            Id = 5,
                            Color = "#034e22",
                            CreatedDate = new DateTime(2022, 5, 27, 18, 19, 4, 188, DateTimeKind.Unspecified).AddTicks(5514),
                            Height = 68,
                            Status = 1,
                            Width = 10
                        },
                        new
                        {
                            Id = 6,
                            Color = "#5f5b66",
                            CreatedDate = new DateTime(2022, 2, 10, 0, 55, 32, 65, DateTimeKind.Unspecified).AddTicks(6980),
                            Height = 21,
                            Status = 1,
                            Width = 128
                        },
                        new
                        {
                            Id = 7,
                            Color = "#783805",
                            CreatedDate = new DateTime(2022, 2, 1, 17, 53, 24, 632, DateTimeKind.Unspecified).AddTicks(1162),
                            Height = 39,
                            Status = 1,
                            Width = 177
                        },
                        new
                        {
                            Id = 8,
                            Color = "#4c2553",
                            CreatedDate = new DateTime(2021, 7, 18, 23, 15, 33, 383, DateTimeKind.Unspecified).AddTicks(9138),
                            Height = 88,
                            Status = 1,
                            Width = 78
                        },
                        new
                        {
                            Id = 9,
                            Color = "#161752",
                            CreatedDate = new DateTime(2022, 7, 4, 7, 32, 41, 120, DateTimeKind.Unspecified).AddTicks(230),
                            Height = 193,
                            Status = 1,
                            Width = 169
                        },
                        new
                        {
                            Id = 10,
                            Color = "#740110",
                            CreatedDate = new DateTime(2021, 6, 26, 19, 26, 3, 516, DateTimeKind.Unspecified).AddTicks(8972),
                            Height = 10,
                            Status = 1,
                            Width = 178
                        },
                        new
                        {
                            Id = 11,
                            Color = "#03180c",
                            CreatedDate = new DateTime(2022, 9, 3, 18, 57, 43, 469, DateTimeKind.Unspecified).AddTicks(3744),
                            Height = 93,
                            Status = 1,
                            Width = 42
                        },
                        new
                        {
                            Id = 12,
                            Color = "#04211d",
                            CreatedDate = new DateTime(2021, 7, 14, 12, 16, 28, 630, DateTimeKind.Unspecified).AddTicks(7287),
                            Height = 161,
                            Status = 1,
                            Width = 177
                        },
                        new
                        {
                            Id = 13,
                            Color = "#3b3b60",
                            CreatedDate = new DateTime(2021, 10, 16, 20, 33, 34, 800, DateTimeKind.Unspecified).AddTicks(2722),
                            Height = 31,
                            Status = 1,
                            Width = 36
                        },
                        new
                        {
                            Id = 14,
                            Color = "#692610",
                            CreatedDate = new DateTime(2022, 5, 30, 13, 12, 25, 644, DateTimeKind.Unspecified).AddTicks(1962),
                            Height = 174,
                            Status = 1,
                            Width = 197
                        },
                        new
                        {
                            Id = 15,
                            Color = "#567152",
                            CreatedDate = new DateTime(2022, 4, 14, 3, 42, 50, 325, DateTimeKind.Unspecified).AddTicks(5927),
                            Height = 164,
                            Status = 1,
                            Width = 183
                        },
                        new
                        {
                            Id = 16,
                            Color = "#530f6d",
                            CreatedDate = new DateTime(2021, 4, 21, 6, 53, 56, 424, DateTimeKind.Unspecified).AddTicks(6906),
                            Height = 17,
                            Status = 1,
                            Width = 2
                        },
                        new
                        {
                            Id = 17,
                            Color = "#1e440d",
                            CreatedDate = new DateTime(2021, 3, 21, 16, 18, 34, 305, DateTimeKind.Unspecified).AddTicks(685),
                            Height = 126,
                            Status = 1,
                            Width = 193
                        },
                        new
                        {
                            Id = 18,
                            Color = "#1e1b25",
                            CreatedDate = new DateTime(2021, 11, 29, 15, 22, 50, 808, DateTimeKind.Unspecified).AddTicks(2925),
                            Height = 129,
                            Status = 1,
                            Width = 89
                        },
                        new
                        {
                            Id = 19,
                            Color = "#6c401b",
                            CreatedDate = new DateTime(2021, 7, 28, 11, 24, 22, 797, DateTimeKind.Unspecified).AddTicks(6304),
                            Height = 96,
                            Status = 1,
                            Width = 105
                        },
                        new
                        {
                            Id = 20,
                            Color = "#7d0b16",
                            CreatedDate = new DateTime(2021, 9, 15, 19, 11, 29, 481, DateTimeKind.Unspecified).AddTicks(6828),
                            Height = 72,
                            Status = 1,
                            Width = 94
                        },
                        new
                        {
                            Id = 21,
                            Color = "#7a0c53",
                            CreatedDate = new DateTime(2021, 11, 15, 20, 38, 58, 515, DateTimeKind.Unspecified).AddTicks(2138),
                            Height = 183,
                            Status = 1,
                            Width = 32
                        },
                        new
                        {
                            Id = 22,
                            Color = "#2e213b",
                            CreatedDate = new DateTime(2021, 8, 5, 0, 18, 40, 901, DateTimeKind.Unspecified).AddTicks(7681),
                            Height = 80,
                            Status = 1,
                            Width = 110
                        },
                        new
                        {
                            Id = 23,
                            Color = "#39126d",
                            CreatedDate = new DateTime(2021, 12, 25, 1, 1, 3, 481, DateTimeKind.Unspecified).AddTicks(8845),
                            Height = 20,
                            Status = 1,
                            Width = 100
                        },
                        new
                        {
                            Id = 24,
                            Color = "#127e4e",
                            CreatedDate = new DateTime(2022, 3, 1, 12, 7, 37, 226, DateTimeKind.Unspecified).AddTicks(7121),
                            Height = 9,
                            Status = 1,
                            Width = 38
                        },
                        new
                        {
                            Id = 25,
                            Color = "#2d576a",
                            CreatedDate = new DateTime(2022, 10, 30, 8, 43, 48, 102, DateTimeKind.Unspecified).AddTicks(5411),
                            Height = 69,
                            Status = 1,
                            Width = 196
                        },
                        new
                        {
                            Id = 26,
                            Color = "#394e68",
                            CreatedDate = new DateTime(2021, 12, 10, 8, 54, 42, 466, DateTimeKind.Unspecified).AddTicks(853),
                            Height = 190,
                            Status = 1,
                            Width = 82
                        },
                        new
                        {
                            Id = 27,
                            Color = "#1e781c",
                            CreatedDate = new DateTime(2022, 7, 16, 17, 1, 9, 373, DateTimeKind.Unspecified).AddTicks(6085),
                            Height = 138,
                            Status = 1,
                            Width = 177
                        },
                        new
                        {
                            Id = 28,
                            Color = "#6e203c",
                            CreatedDate = new DateTime(2021, 12, 4, 19, 9, 49, 290, DateTimeKind.Unspecified).AddTicks(5486),
                            Height = 137,
                            Status = 1,
                            Width = 114
                        },
                        new
                        {
                            Id = 29,
                            Color = "#77761b",
                            CreatedDate = new DateTime(2022, 11, 9, 2, 55, 16, 365, DateTimeKind.Unspecified).AddTicks(4053),
                            Height = 154,
                            Status = 1,
                            Width = 111
                        },
                        new
                        {
                            Id = 30,
                            Color = "#1e4705",
                            CreatedDate = new DateTime(2021, 5, 2, 20, 4, 44, 27, DateTimeKind.Unspecified).AddTicks(7195),
                            Height = 172,
                            Status = 1,
                            Width = 56
                        });
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserLanguage", b =>
                {
                    b.HasOne("NLayer.Core.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLayer.Core.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUserProfile", b =>
                {
                    b.HasOne("NLayer.Core.Models.AppUser", "AppUser")
                        .WithOne("AppUserProfile")
                        .HasForeignKey("NLayer.Core.Models.AppUserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.HasOne("NLayer.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NLayer.Core.Models.ProductFeature", b =>
                {
                    b.HasOne("NLayer.Core.Models.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("NLayer.Core.Models.ProductFeature", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NLayer.Core.Models.AppUser", b =>
                {
                    b.Navigation("AppUserProfile");
                });

            modelBuilder.Entity("NLayer.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NLayer.Core.Models.Product", b =>
                {
                    b.Navigation("ProductFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
